import {
  PRODUCT_IMAGES,
  IMG_ORANGE,
  IMG_BANANA,
  IMG_GRAPES,
  IMG_STRAWBERRY,
  IMG_PAPAYA,
  IMG_MANGO,
  IMG_WATERMELON,
  IMG_BROCCOLI,
  IMG_CARROT,
  IMG_ONION,
  IMG_POTATO,
  IMG_LETTUCE,
  IMG_CILANTRO,
  IMG_BEEF_STEAK,
  IMG_GROUND_BEEF,
  IMG_PORK,
  IMG_FISH,
  IMG_YOGURT,
  IMG_RICE,
  IMG_WATER,
  IMG_PASTA,
} from "@/lib/images"

// Shared product catalog for Resurte.me — Central de Abastos Digital.
// Single-supplier catalog: no per-store pricing, one shared price list.
export const MOCK_PRODUCTS = [
  {
    id: 1,
    name: "Manzana Roja",
    slug: "manzana-roja",
    description: "Manzana roja de huerto local, jugosa y de pulpa firme. Perfecta para cocina en frío y caliente.",
    image_url: PRODUCT_IMAGES["Manzana Roja"],
    brand: "Local",
    category_id: 1,
    show_in_whatsapp: true,
    whatsapp_product_id: null,
    price: 45,
    sale_price: 39,
    unit: "por kilo",
    stock_status: "in_stock" as const,
  },
  {
    id: 2,
    name: "Aguacate Hass",
    slug: "aguacate-hass",
    description: "Aguacate Hass de Michoacán, madurez perfecta. Pulpa cremosa ideal para guacamole de servicio.",
    image_url: PRODUCT_IMAGES["Aguacate Hass"],
    brand: "Michoacán",
    category_id: 1,
    show_in_whatsapp: true,
    whatsapp_product_id: null,
    price: 25,
    sale_price: null,
    unit: "por pieza",
    stock_status: "in_stock" as const,
  },
  {
    id: 3,
    name: "Leche Entera Lala 1L",
    slug: "leche-entera-lala-1l",
    description: "Leche entera pasteurizada de vacas libres. Sabor completo, cuerpo aterciopelado.",
    image_url: PRODUCT_IMAGES["Leche Entera Lala 1L"],
    brand: "Lala",
    category_id: 3,
    show_in_whatsapp: false,
    whatsapp_product_id: null,
    price: 28,
    sale_price: null,
    unit: "1 litro",
    stock_status: "in_stock" as const,
  },
  {
    id: 4,
    name: "Pan Bimbo Blanco",
    slug: "pan-bimbo-blanco",
    description: "Pan de caja blanco de miga suave. Estructura firme, no se desmorona.",
    image_url: PRODUCT_IMAGES["Pan Bimbo Blanco"],
    brand: "Bimbo",
    category_id: 5,
    show_in_whatsapp: false,
    whatsapp_product_id: null,
    price: 42,
    sale_price: 38,
    unit: "680 g",
    stock_status: "in_stock" as const,
  },
  {
    id: 5,
    name: "Pechuga de Pollo",
    slug: "pechuga-pollo",
    description: "Pechuga de pollo fresca, sin piel ni hormonas. Jugosa, lista para plancha o parrilla.",
    image_url: PRODUCT_IMAGES["Pechuga de Pollo"],
    brand: "Bachoco",
    category_id: 4,
    show_in_whatsapp: false,
    whatsapp_product_id: null,
    price: 120,
    sale_price: null,
    unit: "por kilo",
    stock_status: "low_stock" as const,
  },
  {
    id: 6,
    name: "Tortillas de Maíz",
    slug: "tortillas-maiz",
    description: "Tortillas de maíz nixtamalizado, hechas al día. Aroma y sabor de molino.",
    image_url: PRODUCT_IMAGES["Tortillas de Maíz"],
    brand: "Local",
    category_id: 5,
    show_in_whatsapp: true,
    whatsapp_product_id: null,
    price: 22,
    sale_price: null,
    unit: "paquete 1 kg",
    stock_status: "in_stock" as const,
  },
  {
    id: 7,
    name: "Coca-Cola 2.5L",
    slug: "coca-cola-25l",
    description: "Refresco Coca-Cola. Botella de 2.5 litros.",
    image_url: PRODUCT_IMAGES["Coca-Cola 2.5L"],
    brand: "Coca-Cola",
    category_id: 6,
    show_in_whatsapp: false,
    whatsapp_product_id: null,
    price: 38,
    sale_price: null,
    unit: "2.5 litros",
    stock_status: "in_stock" as const,
  },
  {
    id: 8,
    name: "Jitomate Saladet",
    slug: "jitomate-saladet",
    description: "Jitomate saladet de campo, color rojo profundo y pulpa carnosa. Ideal para salsas madre.",
    image_url: PRODUCT_IMAGES["Jitomate Saladet"],
    brand: "Local",
    category_id: 1,
    show_in_whatsapp: true,
    whatsapp_product_id: null,
    price: 28,
    sale_price: 24,
    unit: "por kilo",
    stock_status: "in_stock" as const,
  },
  {
    id: 9,
    name: "Huevo Blanco 18pz",
    slug: "huevo-blanco-18pz",
    description: "Huevo blanco de gallina libre. Clara firme, yema color naranja intenso.",
    image_url: PRODUCT_IMAGES["Huevo Blanco 18pz"],
    brand: "San Juan",
    category_id: 3,
    show_in_whatsapp: false,
    whatsapp_product_id: null,
    price: 56,
    sale_price: null,
    unit: "18 piezas",
    stock_status: "in_stock" as const,
  },
  {
    id: 10,
    name: "Queso Oaxaca",
    slug: "queso-oaxaca",
    description: "Queso Oaxaca artesanal, hebra larga y sabor lácteo limpio. Fundido perfecto.",
    image_url: PRODUCT_IMAGES["Queso Oaxaca"],
    brand: "Local",
    category_id: 3,
    show_in_whatsapp: true,
    whatsapp_product_id: null,
    price: 65,
    sale_price: 58,
    unit: "400 g",
    stock_status: "in_stock" as const,
  },
  {
    id: 11,
    name: "Aceite de Canola 1L",
    slug: "aceite-canola-1l",
    description: "Aceite vegetal de canola, punto de humo alto. Neutro, no interfiere con los sabores.",
    image_url: PRODUCT_IMAGES["Aceite de Canola 1L"],
    brand: "Capullo",
    category_id: 7,
    show_in_whatsapp: true,
    whatsapp_product_id: null,
    price: 42,
    sale_price: null,
    unit: "1 litro",
    stock_status: "in_stock" as const,
  },
  {
    id: 12,
    name: "Frijol Negro 1kg",
    slug: "frijol-negro-1kg",
    description: "Frijol negro de parcela, grano parejo. Cocción uniforme, sabor terroso profundo.",
    image_url: PRODUCT_IMAGES["Frijol Negro 1kg"],
    brand: "Verde Valle",
    category_id: 7,
    show_in_whatsapp: true,
    whatsapp_product_id: null,
    price: 38,
    sale_price: null,
    unit: "1 kg",
    stock_status: "in_stock" as const,
  },
  {
    id: 13,
    name: "Naranja Valencia",
    slug: "naranja-valencia",
    description: "Naranja Valencia de Veracruz. Jugo dulce, acidez equilibrada. Para jugo de servicio y cocina.",
    image_url: IMG_ORANGE,
    brand: "Local",
    category_id: 1,
    show_in_whatsapp: true,
    whatsapp_product_id: null,
    price: 32,
    sale_price: null,
    unit: "por kilo",
    stock_status: "in_stock" as const,
  },
  {
    id: 14,
    name: "Plátano Tabasco",
    slug: "platano-tabasco",
    description: "Plátano Tabasco de maduración pareja. Dulzor natural, textura cremosa.",
    image_url: IMG_BANANA,
    brand: "Tabasco",
    category_id: 1,
    show_in_whatsapp: true,
    whatsapp_product_id: null,
    price: 22,
    sale_price: null,
    unit: "por kilo",
    stock_status: "in_stock" as const,
  },
  {
    id: 15,
    name: "Uvas Verdes",
    slug: "uvas-verdes",
    description: "Uvas verdes sin semilla de California. Crujientes, dulzor brillante.",
    image_url: IMG_GRAPES,
    brand: "California",
    category_id: 1,
    show_in_whatsapp: true,
    whatsapp_product_id: null,
    price: 68,
    sale_price: null,
    unit: "por kilo",
    stock_status: "in_stock" as const,
  },
  {
    id: 16,
    name: "Fresa",
    slug: "fresa",
    description: "Fresa de Irapuato. Rojo intenso, perfume floral. Para repostería y cocina dulce.",
    image_url: IMG_STRAWBERRY,
    brand: "Local",
    category_id: 1,
    show_in_whatsapp: true,
    whatsapp_product_id: null,
    price: 55,
    sale_price: null,
    unit: "charola 500 g",
    stock_status: "in_stock" as const,
  },
  {
    id: 17,
    name: "Papaya",
    slug: "papaya",
    description: "Papaya Maradol de pulpa naranja profunda. Textura suave, dulzor tropical.",
    image_url: IMG_PAPAYA,
    brand: "Local",
    category_id: 1,
    show_in_whatsapp: true,
    whatsapp_product_id: null,
    price: 42,
    sale_price: null,
    unit: "por pieza",
    stock_status: "in_stock" as const,
  },
  {
    id: 18,
    name: "Mango Ataúlfo",
    slug: "mango-ataulfo",
    description: "Mango Ataúlfo de Chiapas. Carne sin fibra, color dorado y dulzor de miel.",
    image_url: IMG_MANGO,
    brand: "Local",
    category_id: 1,
    show_in_whatsapp: true,
    whatsapp_product_id: null,
    price: 28,
    sale_price: null,
    unit: "por pieza",
    stock_status: "in_stock" as const,
  },
  {
    id: 19,
    name: "Sandía",
    slug: "sandia",
    description: "Sandía de temporal, pulpa roja crujiente y jugosa. Refrescante.",
    image_url: IMG_WATERMELON,
    brand: "Local",
    category_id: 1,
    show_in_whatsapp: true,
    whatsapp_product_id: null,
    price: 18,
    sale_price: null,
    unit: "por kilo",
    stock_status: "in_stock" as const,
  },
  {
    id: 20,
    name: "Brócoli",
    slug: "brocoli",
    description: "Brócoli de tallo firme y floretes compactos. Color verde intenso, sabor vegetal limpio.",
    image_url: IMG_BROCCOLI,
    brand: "Local",
    category_id: 1,
    show_in_whatsapp: true,
    whatsapp_product_id: null,
    price: 28,
    sale_price: null,
    unit: "por pieza",
    stock_status: "in_stock" as const,
  },
  {
    id: 21,
    name: "Zanahoria",
    slug: "zanahoria",
    description: "Zanahoria de tierra negra, dulzor natural y color naranja vivo. Cruda o cocida.",
    image_url: IMG_CARROT,
    brand: "Local",
    category_id: 1,
    show_in_whatsapp: true,
    whatsapp_product_id: null,
    price: 18,
    sale_price: null,
    unit: "por kilo",
    stock_status: "in_stock" as const,
  },
  {
    id: 22,
    name: "Cebolla Blanca",
    slug: "cebolla-blanca",
    description: "Cebolla blanca de bulbo firme. Picor limpio, base aromática esencial.",
    image_url: IMG_ONION,
    brand: "Local",
    category_id: 1,
    show_in_whatsapp: true,
    whatsapp_product_id: null,
    price: 22,
    sale_price: null,
    unit: "por kilo",
    stock_status: "in_stock" as const,
  },
  {
    id: 23,
    name: "Papa Blanca",
    slug: "papa-blanca",
    description: "Papa blanca de tierra suelta. Piel fina, pulpa versátil. Para puré, fritura o guisos.",
    image_url: IMG_POTATO,
    brand: "Local",
    category_id: 1,
    show_in_whatsapp: true,
    whatsapp_product_id: null,
    price: 25,
    sale_price: null,
    unit: "por kilo",
    stock_status: "in_stock" as const,
  },
  {
    id: 24,
    name: "Lechuga Romana",
    slug: "lechuga-romana",
    description: "Lechuga romana de hoja crujiente y nervadura firme. Base ideal para ensaladas César.",
    image_url: IMG_LETTUCE,
    brand: "Local",
    category_id: 1,
    show_in_whatsapp: true,
    whatsapp_product_id: null,
    price: 30,
    sale_price: null,
    unit: "por pieza",
    stock_status: "in_stock" as const,
  },
  {
    id: 25,
    name: "Cilantro",
    slug: "cilantro",
    description: "Cilantro fresco de rama verde brillante. Aroma cítrico intenso. Toque final para cualquier plato.",
    image_url: IMG_CILANTRO,
    brand: "Local",
    category_id: 1,
    show_in_whatsapp: true,
    whatsapp_product_id: null,
    price: 12,
    sale_price: null,
    unit: "por manojo",
    stock_status: "in_stock" as const,
  },
  {
    id: 26,
    name: "Bistec de Res",
    slug: "bistec-de-res",
    description: "Bistec de res seleccionado, marmoleo parejo. Suave al corte, sabor profundo.",
    image_url: IMG_BEEF_STEAK,
    brand: "Local",
    category_id: 4,
    show_in_whatsapp: false,
    whatsapp_product_id: null,
    price: 180,
    sale_price: null,
    unit: "por kilo",
    stock_status: "in_stock" as const,
  },
  {
    id: 27,
    name: "Carne Molida",
    slug: "carne-molida",
    description: "Carne molida de res magra 80/20. Textura uniforme, sazón base para cocina de volumen.",
    image_url: IMG_GROUND_BEEF,
    brand: "Local",
    category_id: 4,
    show_in_whatsapp: false,
    whatsapp_product_id: null,
    price: 145,
    sale_price: null,
    unit: "por kilo",
    stock_status: "in_stock" as const,
  },
  {
    id: 28,
    name: "Chuleta de Cerdo",
    slug: "chuleta-de-cerdo",
    description: "Chuleta de cerdo de corte parejo. Carne tierna con hueso para máximo sabor.",
    image_url: IMG_PORK,
    brand: "Local",
    category_id: 4,
    show_in_whatsapp: false,
    whatsapp_product_id: null,
    price: 135,
    sale_price: null,
    unit: "por kilo",
    stock_status: "in_stock" as const,
  },
  {
    id: 29,
    name: "Filete de Tilapia",
    slug: "filete-de-tilapia",
    description: "Filete de tilapia fresco de agua dulce. Carne blanca firme, sabor limpio.",
    image_url: IMG_FISH,
    brand: "Local",
    category_id: 4,
    show_in_whatsapp: false,
    whatsapp_product_id: null,
    price: 150,
    sale_price: null,
    unit: "por kilo",
    stock_status: "in_stock" as const,
  },
  {
    id: 30,
    name: "Yogurt Natural 1L",
    slug: "yogurt-natural-1l",
    description: "Yogurt natural sin azúcar añadida. Textura sedosa, acidez balanceada. Para cocina y servicio.",
    image_url: IMG_YOGURT,
    brand: "Yoplait",
    category_id: 3,
    show_in_whatsapp: false,
    whatsapp_product_id: null,
    price: 38,
    sale_price: null,
    unit: "1 litro",
    stock_status: "in_stock" as const,
  },
  {
    id: 31,
    name: "Arroz 1kg",
    slug: "arroz-1kg",
    description: "Arroz blanco de grano largo, cocción pareja. Base neutra para cocina de servicio.",
    image_url: IMG_RICE,
    brand: "Verde Valle",
    category_id: 7,
    show_in_whatsapp: false,
    whatsapp_product_id: null,
    price: 28,
    sale_price: null,
    unit: "1 kg",
    stock_status: "in_stock" as const,
  },
  {
    id: 32,
    name: "Agua Bonafont 1.5L",
    slug: "agua-bonafont-1-5l",
    description: "Agua purificada con mineralización ligera. Sabor neutro, perfecta para servicio.",
    image_url: IMG_WATER,
    brand: "Bonafont",
    category_id: 6,
    show_in_whatsapp: false,
    whatsapp_product_id: null,
    price: 15,
    sale_price: null,
    unit: "1.5 litros",
    stock_status: "in_stock" as const,
  },
  {
    id: 33,
    name: "Pasta Spaghetti",
    slug: "pasta-spaghetti",
    description: "Pasta spaghetti de sémola de trigo duro. Cuerpo firme al dente, no se sobrecocina.",
    image_url: IMG_PASTA,
    brand: "Barilla",
    category_id: 7,
    show_in_whatsapp: false,
    whatsapp_product_id: null,
    price: 18,
    sale_price: null,
    unit: "500 g",
    stock_status: "in_stock" as const,
  },
]

export const MOCK_CATEGORIES = [
  { id: 1, name: "Frutas y Verduras", icon: "🥬", slug: "frutas-verduras", description: "Del campo a tu cocina. Producto fresco seleccionado cada mañana." },
  { id: 3, name: "Lácteos y Huevos", icon: "🧀", slug: "lacteos-huevos", description: "Lácteos, quesos y huevo fresco de granja. Calidad que se nota." },
  { id: 4, name: "Carnes y Pescados", icon: "🥩", slug: "carnes-pescados", description: "Cortes selectos, carne de res, pollo y cerdo. Frescura garantizada." },
  { id: 5, name: "Panadería y Tortillería", icon: "🍞", slug: "panaderia-tortilleria", description: "Pan recién horneado y tortillas del día. El aroma de lo fresco." },
  { id: 6, name: "Bebidas", icon: "🥤", slug: "bebidas", description: "Aguas, refrescos y bebidas. Todo para acompañar." },
  { id: 7, name: "Despensa", icon: "🥫", slug: "despensa", description: "Abarrotes, granos, aceites y conservas. Lo básico siempre a la mano." },
  { id: 8, name: "Limpieza", icon: "🧹", slug: "limpieza", description: "Productos de limpieza para mantener tu cocina impecable." },
  { id: 11, name: "Mascotas", icon: "🐾", slug: "mascotas", description: "Alimento y accesorios para las mascotas de tu negocio." },
]
