/**
 * Collection Recipes — Recetario por tipo de colección.
 *
 * Cada colección incluye recetas representativas con sus ingredientes,
 * para que los dueños de restaurante encuentren inspiración y
 * descubran qué insumos necesitan para preparar esos platillos.
 */
import type { CollectionRecipe } from "@/types"

type RecipeInput = Omit<CollectionRecipe, "id" | "collection_id" | "is_active">

export interface RecipeGroup {
  collectionSlug: string
  recipes: RecipeInput[]
}

const RECIPES: Record<string, RecipeInput[]> = {
  // ── 1. Hamburguesas y Hot Dogs ──────────────────────────
  "hamburguesas-hot-dogs": [
    {
      name: "Hamburguesa Clásica Smash",
      description: "Doble carne smash con queso cheddar fundido, pepinillos y cebolla caramelizada en pan brioche.",
      ingredients: ["Carne molida 80/20", "Pan brioche", "Queso cheddar rebanado", "Pepinillos", "Cebolla blanca", "Lechuga", "Jitomate bola", "Mostaza", "Catsup"],
      prep_time: "25 min",
      servings: "4 porciones",
      image_url: "/images/recipes/burger-smash.webp",
      display_order: 1,
    },
    {
      name: "Hot Dog Estilo Chicago",
      description: "Salchicha jumbo en pan suave con pepinillos, tomate, cebolla, chiles sport y mostaza amarilla.",
      ingredients: ["Salchicha jumbo", "Pan para hot dog", "Pepinillos encurtidos", "Jitomate bola", "Cebolla blanca", "Chiles jalapeños", "Mostaza amarilla", "Catsup"],
      prep_time: "20 min",
      servings: "6 porciones",
      image_url: "/images/recipes/hotdog-chicago.webp",
      display_order: 2,
    },
    {
      name: "Papas Fritas Gourmet",
      description: "Papas fritas crujientes con queso cheddar, tocino y cebollín. Acompañamiento infalible.",
      ingredients: ["Papas congeladas", "Queso cheddar rebanado", "Tocino", "Cebolla blanca", "Aceite vegetal"],
      prep_time: "15 min",
      servings: "4 porciones",
      image_url: "/images/recipes/papas-gourmet.webp",
      display_order: 3,
    },
    {
      name: "Hamburguesa BBQ Bacon",
      description: "Carne de res con tocino crujiente, aros de cebolla y salsa BBQ ahumada en pan brioche.",
      ingredients: ["Carne molida 80/20", "Pan brioche", "Tocino", "Queso cheddar rebanado", "Aros de cebolla", "Salsa BBQ", "Lechuga"],
      prep_time: "25 min",
      servings: "4 porciones",
      image_url: "/images/recipes/hamburguesa-bbq-bacon.webp",
      display_order: 4,
    },
    {
      name: "Hot Dog Estilo Sonora",
      description: "Salchicha envuelta en tocino con frijoles, jitomate, cebolla y mayonesa. Especialidad del norte.",
      ingredients: ["Salchicha envuelta en tocino", "Pan para hot dog", "Frijoles refritos", "Jitomate saladet", "Cebolla blanca", "Mayonesa", "Chile jalapeño"],
      prep_time: "20 min",
      servings: "6 porciones",
      image_url: "/images/recipes/hotdog-sonora.webp",
      display_order: 5,
    },
    {
      name: "Aros de Cebolla Empanizados",
      description: "Aros de cebolla crujientes rebozados en panko, servidos con aderezo ranch.",
      ingredients: ["Cebolla blanca", "Panko", "Harina de trigo", "Huevo fresco", "Aceite vegetal", "Aderezo ranch"],
      prep_time: "20 min",
      servings: "4 porciones",
      image_url: "/images/recipes/aros-de-cebolla.webp",
      display_order: 6,
    },
  ],

  // ── 2. Taquerías y Antojitos ──────────────────────────
  "taquerias-antojitos": [
    {
      name: "Tacos al Pastor",
      description: "Carne de cerdo marinada en achiote, cocinada en trompo y servida con piña, cebolla y cilantro.",
      ingredients: ["Pierna de cerdo", "Achiote en pasta", "Piña miel", "Cebolla blanca", "Cilantro fresco", "Tortillas de maíz", "Chiles secos", "Vinagre"],
      prep_time: "2 hrs (marinado) + 30 min",
      servings: "20 tacos",
      image_url: "/images/recipes/tacos-pastor.webp",
      display_order: 1,
    },
    {
      name: "Tacos de Bistec",
      description: "Bistec de res a la plancha con cebolla asada, cilantro y salsa roja. El clásico de toda taquería.",
      ingredients: ["Bistec de res", "Cebolla cambray", "Cilantro fresco", "Tortillas de maíz", "Limón agrio", "Chile guajillo"],
      prep_time: "30 min",
      servings: "15 tacos",
      image_url: "/images/recipes/tacos-bistec.webp",
      display_order: 2,
    },
    {
      name: "Sopes de Pollo",
      description: "Sopes de masa gruesa con frijoles refritos, pollo deshebrado, lechuga, crema y queso fresco.",
      ingredients: ["Harina de maíz", "Pechuga de pollo", "Frijoles refritos", "Crema ácida", "Queso fresco", "Lechuga", "Jitomate saladet"],
      prep_time: "45 min",
      servings: "8 sopes",
      image_url: "/images/recipes/sopes-pollo.webp",
      display_order: 3,
    },
    {
      name: "Tacos de Carnitas",
      description: "Cerdo confitado en su propia grasa, deshebrado y servido con cebolla, cilantro y salsa verde.",
      ingredients: ["Pierna de cerdo", "Manteca de cerdo", "Naranja Valencia", "Hoja de laurel", "Cebolla blanca", "Cilantro fresco", "Tortillas de maíz"],
      prep_time: "3 hrs",
      servings: "20 tacos",
      image_url: "/images/recipes/tacos-carnitas.webp",
      display_order: 4,
    },
    {
      name: "Quesadillas de Flor de Calabaza",
      description: "Tortilla de maíz rellena de flor de calabaza, queso Oaxaca y epazote.",
      ingredients: ["Tortillas de maíz", "Flor de calabaza", "Queso Oaxaca", "Epazote", "Cebolla blanca", "Aceite vegetal"],
      prep_time: "25 min",
      servings: "10 quesadillas",
      image_url: "/images/recipes/quesadillas-flor-calabaza.webp",
      display_order: 5,
    },
    {
      name: "Tostadas de Tinga",
      description: "Tostadas crujientes con pollo deshebrado en salsa de chipotle, frijoles y crema.",
      ingredients: ["Tostadas", "Pechuga de pollo", "Chile chipotle", "Jitomate saladet", "Cebolla blanca", "Frijoles refritos", "Crema ácida", "Queso fresco"],
      prep_time: "40 min",
      servings: "10 tostadas",
      image_url: "/images/recipes/tostadas-tinga.webp",
      display_order: 6,
    },
  ],

  // ── 3. Sushi y Comida Asiática ─────────────────────────
  "sushi-comida-asiatica": [
    {
      name: "California Roll",
      description: "Rollo clásico con surimi, aguacate y pepino envuelto en arroz y alga nori con ajonjolí.",
      ingredients: ["Arroz para sushi", "Alga nori", "Surimi", "Aguacate hass", "Pepino", "Ajonjolí", "Salsa de soya", "Jengibre encurtido"],
      prep_time: "40 min",
      servings: "4 rollos (32 piezas)",
      image_url: "/images/recipes/california-roll.webp",
      display_order: 1,
    },
    {
      name: "Ramen Tonkotsu",
      description: "Caldo cremoso de cerdo con fideos, huevo, naruto y cebollín. El rey de los ramen.",
      ingredients: ["Huesos de cerdo", "Fideos ramen", "Huevo fresco", "Cebolla cambray", "Ajo", "Jengibre", "Salsa de soya"],
      prep_time: "4 hrs (caldo) + 30 min",
      servings: "4 tazones",
      image_url: "/images/recipes/ramen-tonkotsu.webp",
      display_order: 2,
    },
    {
      name: "Pollo Teriyaki",
      description: "Muslos de pollo glaseados en salsa teriyaki con arroz al vapor y verduras salteadas.",
      ingredients: ["Pierna y muslo de pollo", "Salsa de soya", "Azúcar", "Jengibre", "Ajo", "Arroz para sushi", "Brócoli", "Zanahoria"],
      prep_time: "35 min",
      servings: "4 porciones",
      image_url: "/images/recipes/pollo-teriyaki.webp",
      display_order: 3,
    },
    {
      name: "Gyozas de Cerdo",
      description: "Empanaditas japonesas rellenas de cerdo y col, doradas y al vapor, con salsa de soya.",
      ingredients: ["Carne de cerdo molida", "Col china", "Cebollín", "Jengibre", "Ajo", "Pasta wonton", "Salsa de soya"],
      prep_time: "45 min",
      servings: "20 piezas",
      image_url: "/images/recipes/gyozas-cerdo.webp",
      display_order: 4,
    },
    {
      name: "Pad Thai de Camarón",
      description: "Fideos de arroz salteados con camarón, huevo, tamarindo y cacahuate. Sabor tailandés auténtico.",
      ingredients: ["Fideos de arroz", "Camarón", "Huevo fresco", "Pasta de tamarindo", "Cacahuate", "Germinado de soya", "Cebollín"],
      prep_time: "30 min",
      servings: "4 porciones",
      image_url: "/images/recipes/pad-thai.webp",
      display_order: 5,
    },
    {
      name: "Sushi Roll Dragón",
      description: "Rollo de camarón tempura cubierto con aguacate en rebanadas y salsa de anguila.",
      ingredients: ["Arroz para sushi", "Alga nori", "Camarón", "Aguacate hass", "Pepino", "Salsa de anguila", "Ajonjolí"],
      prep_time: "45 min",
      servings: "4 rollos (32 piezas)",
      image_url: "/images/recipes/sushi-dragon.webp",
      display_order: 6,
    },
  ],

  // ── 4. Pizzas y Comida Italiana ──────────────────────
  "pizzas-comida-italiana": [
    {
      name: "Pizza Margherita Clásica",
      description: "Masa fina con salsa de tomate San Marzano, mozzarella fresca y albahaca. La reina de Nápoles.",
      ingredients: ["Harina de trigo", "Puré de tomate enlatado", "Queso mozzarella", "Albahaca fresca", "Aceite de oliva", "Sal", "Levadura"],
      prep_time: "2 hrs (masa) + 15 min",
      servings: "2 pizzas medianas",
      image_url: "/images/recipes/pizza-margherita.webp",
      display_order: 1,
    },
    {
      name: "Pizza Pepperoni Supreme",
      description: "Masa gruesa estilo americano con pepperoni, champiñones, pimiento y extra queso.",
      ingredients: ["Harina de trigo", "Puré de tomate enlatado", "Queso mozzarella", "Pepperoni", "Champiñones frescos", "Pimiento morrón"],
      prep_time: "2 hrs (masa) + 20 min",
      servings: "2 pizzas grandes",
      image_url: "/images/recipes/pizza-pepperoni.webp",
      display_order: 2,
    },
    {
      name: "Pasta Alfredo con Pollo",
      description: "Fettuccine en salsa cremosa de mantequilla y parmesano con pechuga de pollo dorada.",
      ingredients: ["Pasta fettuccine", "Pechuga de pollo", "Mantequilla", "Queso parmesano", "Crema para batir", "Ajo", "Pimienta negra"],
      prep_time: "30 min",
      servings: "4 porciones",
      image_url: "/images/recipes/pasta-alfredo.webp",
      display_order: 3,
    },
    {
      name: "Pizza Cuatro Quesos",
      description: "Mozzarella, gorgonzola, parmesano y provolone sobre masa artesanal. Intensa y cremosa.",
      ingredients: ["Harina de trigo", "Queso mozzarella", "Queso gorgonzola", "Queso parmesano", "Queso provolone", "Aceite de oliva", "Levadura"],
      prep_time: "2 hrs (masa) + 15 min",
      servings: "2 pizzas medianas",
      image_url: "/images/recipes/pizza-cuatro-quesos.webp",
      display_order: 4,
    },
    {
      name: "Lasaña Boloñesa",
      description: "Capas de pasta, carne molida en salsa boloñesa, bechamel y queso gratinado.",
      ingredients: ["Pasta para lasaña", "Carne molida 80/20", "Jitomate en puré", "Leche entera", "Mantequilla", "Harina de trigo", "Queso parmesano", "Queso mozzarella"],
      prep_time: "1.5 hrs",
      servings: "8 porciones",
      image_url: "/images/recipes/lasana-bolonesa.webp",
      display_order: 5,
    },
    {
      name: "Tiramisú Clásico",
      description: "Postre italiano de capas de soletillas al café, mascarpone y cocoa espolvoreada.",
      ingredients: ["Soletillas", "Queso mascarpone", "Café espresso", "Huevo fresco", "Azúcar", "Cocoa en polvo"],
      prep_time: "30 min + 4 hrs refrigeración",
      servings: "10 porciones",
      image_url: "/images/recipes/tiramisu.webp",
      display_order: 6,
    },
  ],

  // ── 5. Pollo y Alitas ──────────────────────────────
  "pollo-alitas": [
    {
      name: "Alitas Buffalo Clásicas",
      description: "Alitas fritas crujientes bañadas en salsa buffalo picante con aderezo blue cheese.",
      ingredients: ["Alitas de pollo", "Salsa buffalo", "Mantequilla", "Aceite vegetal", "Apio", "Zanahoria", "Queso azul"],
      prep_time: "35 min",
      servings: "24 alitas",
      image_url: "/images/recipes/alitas-buffalo.webp",
      display_order: 1,
    },
    {
      name: "Boneless BBQ",
      description: "Trozos de pechuga empanizados bañados en salsa BBQ ahumada. El favorito de todos.",
      ingredients: ["Pechuga de pollo", "Pan molido", "Huevo fresco", "Salsa BBQ", "Aceite vegetal"],
      prep_time: "30 min",
      servings: "6 porciones",
      image_url: "/images/recipes/boneless-bbq.webp",
      display_order: 2,
    },
    {
      name: "Pollo Rostizado",
      description: "Pollo entero rostizado con hierbas, ajo y limón. Piel dorada, carne jugosa. Ideal para servicio diario.",
      ingredients: ["Pollo entero", "Ajo", "Limón agrio", "Romero", "Tomillo", "Mantequilla", "Papas cambray"],
      prep_time: "1.5 hrs",
      servings: "1 pollo (4-6 porciones)",
      image_url: "/images/recipes/pollo-rostizado.webp",
      display_order: 3,
    },
    {
      name: "Alitas Mango Habanero",
      description: "Alitas fritas bañadas en salsa dulce de mango con toque picante de chile habanero.",
      ingredients: ["Alitas de pollo", "Mango", "Chile habanero", "Miel de abeja", "Vinagre", "Ajo", "Aceite vegetal"],
      prep_time: "35 min",
      servings: "24 alitas",
      image_url: "/images/recipes/alitas-mango-habanero.webp",
      display_order: 4,
    },
    {
      name: "Alitas al Ajillo",
      description: "Alitas doradas salteadas en abundante ajo, mantequilla y perejil. Sencillas y deliciosas.",
      ingredients: ["Alitas de pollo", "Ajo", "Mantequilla", "Perejil fresco", "Limón agrio", "Aceite de oliva"],
      prep_time: "30 min",
      servings: "24 alitas",
      image_url: "/images/recipes/alitas-ajillo.webp",
      display_order: 5,
    },
    {
      name: "Tenders de Pollo Empanizados",
      description: "Tiras de pechuga empanizadas y fritas, crujientes por fuera y jugosas por dentro.",
      ingredients: ["Pechuga de pollo", "Pan molido", "Huevo fresco", "Harina de trigo", "Aceite vegetal", "Sal", "Pimienta"],
      prep_time: "30 min",
      servings: "6 porciones",
      image_url: "/images/recipes/tenders-pollo.webp",
      display_order: 6,
    },
  ],

  // ── 6. Comida Mexicana / Comida Corrida ─────────────
  "comida-mexicana-corrida": [
    {
      name: "Chiles Rellenos",
      description: "Chiles poblanos rellenos de queso, capeados y bañados en caldillo de jitomate. Clásico de comida corrida.",
      ingredients: ["Chile poblano", "Queso asadero", "Huevo fresco", "Jitomate saladet", "Cebolla blanca", "Ajo", "Aceite vegetal"],
      prep_time: "1 hr",
      servings: "6 chiles",
      image_url: "/images/recipes/chiles-rellenos.webp",
      display_order: 1,
    },
    {
      name: "Mole Poblano",
      description: "Mole tradicional con variedad de chiles secos, chocolate y especias. La joya de la comida mexicana.",
      ingredients: ["Chile mulato", "Chile ancho", "Chile pasilla", "Chocolate de mesa", "Ajonjolí", "Almendras", "Pasas", "Plátano macho", "Pollo entero"],
      prep_time: "3 hrs",
      servings: "12 porciones",
      image_url: "/images/recipes/mole-poblano.webp",
      display_order: 2,
    },
    {
      name: "Enchiladas Verdes",
      description: "Tortillas rellenas de pollo bañadas en salsa verde, gratinadas con crema y queso.",
      ingredients: ["Tortillas de maíz", "Pechuga de pollo", "Tomate verde", "Chile serrano", "Crema ácida", "Queso fresco", "Cilantro fresco"],
      prep_time: "40 min",
      servings: "12 enchiladas",
      image_url: "/images/recipes/enchiladas-verdes.webp",
      display_order: 3,
    },
    {
      name: "Pozole Rojo",
      description: "Caldo de maíz cacahuazintle con carne de cerdo y chile guajillo, servido con lechuga y rábano.",
      ingredients: ["Maíz cacahuazintle", "Pierna de cerdo", "Chile guajillo", "Chile ancho", "Ajo", "Cebolla blanca", "Lechuga", "Rábano", "Orégano"],
      prep_time: "3 hrs",
      servings: "10 porciones",
      image_url: "/images/recipes/pozole-rojo.webp",
      display_order: 4,
    },
    {
      name: "Chile en Nogada",
      description: "Chile poblano relleno de picadillo dulce-salado, bañado en nogada y granada. Platillo de temporada.",
      ingredients: ["Chile poblano", "Carne molida 80/20", "Manzana", "Pera", "Nuez de castilla", "Crema ácida", "Queso de cabra", "Granada"],
      prep_time: "2 hrs",
      servings: "6 chiles",
      image_url: "/images/recipes/chile-nogada.webp",
      display_order: 5,
    },
    {
      name: "Tamales Verdes",
      description: "Masa de maíz rellena de pollo en salsa verde, envuelta en hoja de maíz y cocida al vapor.",
      ingredients: ["Masa de maíz para tamal", "Pechuga de pollo", "Tomate verde", "Chile serrano", "Manteca de cerdo", "Hoja de maíz", "Caldo de pollo"],
      prep_time: "2 hrs",
      servings: "20 tamales",
      image_url: "/images/recipes/tamales-verdes.webp",
      display_order: 6,
    },
  ],

  // ── 7. Mariscos y Pescados ─────────────────────────
  "mariscos-pescados": [
    {
      name: "Ceviche de Camarón",
      description: "Camarón cocido en jugo de limón con jitomate, cebolla, cilantro y aguacate. Frescura pura.",
      ingredients: ["Camarón", "Limón agrio", "Jitomate saladet", "Cebolla morada", "Cilantro fresco", "Aguacate hass", "Pepino", "Salsa inglesa"],
      prep_time: "25 min",
      servings: "6 porciones",
      image_url: "/images/recipes/ceviche-camaron.webp",
      display_order: 1,
    },
    {
      name: "Filete de Pescado Empanizado",
      description: "Filete blanco empanizado con panko, dorado y crujiente. Acompañado de ensalada fresca.",
      ingredients: ["Filete de pescado blanco", "Panko", "Huevo fresco", "Harina de trigo", "Lechuga", "Jitomate bola", "Limón agrio"],
      prep_time: "25 min",
      servings: "4 porciones",
      image_url: "/images/recipes/pescado-empanizado.webp",
      display_order: 2,
    },
    {
      name: "Cóctel de Camarón",
      description: "Camarones en salsa de tomate con cebolla, cilantro y aguacate. El clásico de marisquería.",
      ingredients: ["Camarón", "Catsup", "Jugo de tomate", "Cebolla blanca", "Cilantro fresco", "Aguacate hass", "Limón agrio", "Salsa picante"],
      prep_time: "20 min",
      servings: "6 cócteles",
      image_url: "/images/recipes/coctel-camaron.webp",
      display_order: 3,
    },
    {
      name: "Aguachile Verde",
      description: "Camarón fresco en salsa de chile serrano, limón y pepino. Picante y refrescante.",
      ingredients: ["Camarón", "Chile serrano", "Limón agrio", "Pepino", "Cebolla morada", "Cilantro fresco", "Sal"],
      prep_time: "20 min",
      servings: "6 porciones",
      image_url: "/images/recipes/aguachile-verde.webp",
      display_order: 4,
    },
    {
      name: "Camarones al Mojo de Ajo",
      description: "Camarones salteados en abundante ajo y mantequilla, servidos con arroz blanco.",
      ingredients: ["Camarón", "Ajo", "Mantequilla", "Aceite de oliva", "Limón agrio", "Perejil fresco", "Arroz blanco"],
      prep_time: "20 min",
      servings: "4 porciones",
      image_url: "/images/recipes/camarones-mojo-ajo.webp",
      display_order: 5,
    },
    {
      name: "Zarandeado de Pescado",
      description: "Pescado entero marinado en adobo y asado sobre parrilla, estilo Nayarit.",
      ingredients: ["Pescado huachinango entero", "Chile guajillo", "Chile ancho", "Ajo", "Naranja Valencia", "Mayonesa", "Cebolla morada"],
      prep_time: "1 hr",
      servings: "4 porciones",
      image_url: "/images/recipes/zarandeado-pescado.webp",
      display_order: 6,
    },
  ],

  // ── 8. Cortes de Carne y Asaderos ──────────────────
  "cortes-carne-asaderos": [
    {
      name: "Ribeye a la Parrilla",
      description: "Corte ribeye sellado a fuego alto, término medio. Acompañado de papas asadas y chimichurri.",
      ingredients: ["Ribeye", "Sal de grano", "Pimienta negra", "Aceite de oliva", "Papas cambray", "Perejil fresco", "Ajo", "Vinagre"],
      prep_time: "25 min",
      servings: "2 cortes",
      image_url: "/images/recipes/ribeye-parrilla.webp",
      display_order: 1,
    },
    {
      name: "Arrachera a la Parrilla",
      description: "Arrachera marinada en jugo de naranja agria y especias, asada a fuego directo. Tradición norteña.",
      ingredients: ["Arrachera", "Naranja Valencia", "Ajo", "Cebolla blanca", "Sal", "Pimienta", "Cebolla cambray"],
      prep_time: "4 hrs (marinado) + 20 min",
      servings: "4 porciones",
      image_url: "/images/recipes/arrachera.webp",
      display_order: 2,
    },
    {
      name: "Queso Fundido con Chorizo",
      description: "Queso asadero fundido con chorizo mexicano. Servido con tortillas de harina. El rey de las entradas.",
      ingredients: ["Queso asadero", "Chorizo", "Tortillas de harina", "Chile serrano", "Cilantro fresco"],
      prep_time: "15 min",
      servings: "6 porciones",
      image_url: "/images/recipes/queso-fundido.webp",
      display_order: 3,
    },
    {
      name: "T-Bone a la Parrilla",
      description: "Corte T-bone sellado a la parrilla, término a elegir, con papa al horno y mantequilla de hierbas.",
      ingredients: ["T-bone", "Sal de grano", "Pimienta negra", "Mantequilla", "Romero", "Papas cambray", "Aceite de oliva"],
      prep_time: "30 min",
      servings: "2 cortes",
      image_url: "/images/recipes/t-bone.webp",
      display_order: 4,
    },
    {
      name: "Costillas BBQ",
      description: "Costillas de cerdo cocidas lentamente y bañadas en salsa BBQ dulce y ahumada.",
      ingredients: ["Costillas de cerdo", "Salsa BBQ", "Azúcar mascabado", "Pimentón", "Ajo en polvo", "Cebolla en polvo"],
      prep_time: "3 hrs",
      servings: "4 porciones",
      image_url: "/images/recipes/costillas-bbq.webp",
      display_order: 5,
    },
    {
      name: "Tacos de Suadero",
      description: "Suadero de res cocido en su propia grasa, dorado en comal y servido en tortilla de maíz.",
      ingredients: ["Suadero de res", "Manteca de cerdo", "Tortillas de maíz", "Cebolla blanca", "Cilantro fresco", "Salsa verde"],
      prep_time: "2 hrs",
      servings: "20 tacos",
      image_url: "/images/recipes/tacos-suadero.webp",
      display_order: 6,
    },
  ],

  // ── 9. Cafeterías, Crepas y Desayunos ─────────────
  "cafeterias-crepas-desayunos": [
    {
      name: "Crepa Dulce de Nutella y Fresa",
      description: "Crepa francesa delgada rellena de nutella, fresas frescas y crema batida.",
      ingredients: ["Harina de trigo", "Huevo fresco", "Leche entera", "Mantequilla", "Nutella", "Fresa", "Crema para batir"],
      prep_time: "20 min",
      servings: "4 crepas",
      image_url: "/images/recipes/crepa-nutella.webp",
      display_order: 1,
    },
    {
      name: "Huevos Rancheros",
      description: "Huevos estrellados sobre tortilla frita, bañados en salsa roja. El desayuno mexicano por excelencia.",
      ingredients: ["Huevo fresco", "Tortillas de maíz", "Jitomate saladet", "Chile serrano", "Cebolla blanca", "Frijoles refritos", "Aceite vegetal"],
      prep_time: "25 min",
      servings: "4 porciones",
      image_url: "/images/recipes/huevos-rancheros.webp",
      display_order: 2,
    },
    {
      name: "Hot Cakes Americanos",
      description: "Hot cakes esponjosos con mantequilla y miel de maple. Ideal para desayunos y brunch.",
      ingredients: ["Harina para hot cakes", "Huevo fresco", "Leche entera", "Mantequilla", "Miel de maple"],
      prep_time: "20 min",
      servings: "8 hot cakes",
      image_url: "/images/recipes/hotcakes.webp",
      display_order: 3,
    },
    {
      name: "Café Latte Artesanal",
      description: "Espresso con leche vaporizada y espuma cremosa, presentación de casa. Base del menú de cafetería.",
      ingredients: ["Café en grano", "Leche entera", "Azúcar"],
      prep_time: "10 min",
      servings: "1 taza",
      image_url: "/images/recipes/cafe-latte.webp",
      display_order: 4,
    },
    {
      name: "Waffles Belgas",
      description: "Waffles crujientes por fuera y esponjosos por dentro, con frutos rojos y miel de maple.",
      ingredients: ["Harina de trigo", "Huevo fresco", "Leche entera", "Mantequilla", "Fresa", "Zarzamora", "Miel de maple"],
      prep_time: "25 min",
      servings: "4 waffles",
      image_url: "/images/recipes/waffles-belgas.webp",
      display_order: 5,
    },
    {
      name: "Chilaquiles Verdes",
      description: "Totopos bañados en salsa verde, con pollo deshebrado, crema y queso fresco. Desayuno reconfortante.",
      ingredients: ["Totopos", "Tomate verde", "Chile serrano", "Pechuga de pollo", "Crema ácida", "Queso fresco", "Cebolla blanca"],
      prep_time: "25 min",
      servings: "4 porciones",
      image_url: "/images/recipes/chilaquiles-verdes.webp",
      display_order: 6,
    },
  ],

  // ── 10. Saludable, Ensaladas y Pokés ──────────────
  "saludable-ensaladas-pokes": [
    {
      name: "Poké Bowl de Atún",
      description: "Cubos de atún fresco marinado en soya y ajonjolí sobre arroz, con edamame, pepino y aguacate.",
      ingredients: ["Atún fresco", "Arroz para sushi", "Salsa de soya", "Ajonjolí", "Aguacate hass", "Pepino", "Edamame", "Alga nori"],
      prep_time: "20 min",
      servings: "4 bowls",
      image_url: "/images/recipes/poke-atun.webp",
      display_order: 1,
    },
    {
      name: "Ensalada César con Pollo",
      description: "Lechuga romana con pechuga de pollo a la parrilla, crutones, parmesano y aderezo César.",
      ingredients: ["Lechuga romana", "Pechuga de pollo", "Queso parmesano", "Pan para crutones", "Limón agrio", "Aceite de oliva", "Ajo"],
      prep_time: "20 min",
      servings: "4 porciones",
      image_url: "/images/recipes/ensalada-cesar.webp",
      display_order: 2,
    },
    {
      name: "Smoothie Energético Verde",
      description: "Bebida de espinaca, piña, plátano y jengibre. Energía limpia y deliciosa.",
      ingredients: ["Espinaca fresca", "Piña miel", "Plátano tabasco", "Jengibre fresco", "Miel de abeja"],
      prep_time: "10 min",
      servings: "2 smoothies",
      image_url: "/images/recipes/smoothie-verde.webp",
      display_order: 3,
    },
    {
      name: "Poké Bowl de Salmón",
      description: "Cubos de salmón fresco sobre arroz integral con edamame, mango y aderezo de soya-miel.",
      ingredients: ["Salmón fresco", "Arroz integral", "Edamame", "Mango", "Aguacate hass", "Salsa de soya", "Miel de abeja"],
      prep_time: "20 min",
      servings: "4 bowls",
      image_url: "/images/recipes/poke-salon.webp",
      display_order: 4,
    },
    {
      name: "Ensalada Mediterránea de Quinoa",
      description: "Quinoa con pepino, jitomate cherry, aceituna kalamata y queso feta. Fresca y ligera.",
      ingredients: ["Quinoa", "Pepino", "Jitomate cherry", "Aceituna kalamata", "Queso feta", "Aceite de oliva", "Limón agrio"],
      prep_time: "20 min",
      servings: "4 porciones",
      image_url: "/images/recipes/ensalada-mediterranea.webp",
      display_order: 5,
    },
    {
      name: "Wrap de Pollo y Vegetales",
      description: "Tortilla integral rellena de pollo a la plancha, espinaca, zanahoria y aderezo yogur.",
      ingredients: ["Tortilla integral", "Pechuga de pollo", "Espinaca fresca", "Zanahoria", "Yogur griego", "Limón agrio"],
      prep_time: "20 min",
      servings: "4 wraps",
      image_url: "/images/recipes/wrap-pollo.webp",
      display_order: 6,
    },
  ],

  // ── 11. Postres, Panadería y Helados ──────────────
  "postres-panaderia-helados": [
    {
      name: "Pastel de Chocolate",
      description: "Bizcocho húmedo de chocolate con ganache cremoso. El pastel que todo restaurante necesita.",
      ingredients: ["Harina de trigo", "Cocoa en polvo", "Huevo fresco", "Mantequilla", "Azúcar", "Chispas de chocolate", "Crema para batir"],
      prep_time: "1 hr",
      servings: "12 rebanadas",
      image_url: "/images/recipes/pastel-chocolate.webp",
      display_order: 1,
    },
    {
      name: "Conchas Mexicanas",
      description: "Pan dulce tradicional mexicano con cobertura de azúcar. Perfecto para cafeterías y desayunos.",
      ingredients: ["Harina de trigo", "Azúcar", "Mantequilla", "Huevo fresco", "Levadura", "Leche entera", "Vainilla"],
      prep_time: "2.5 hrs",
      servings: "12 conchas",
      image_url: "/images/recipes/conchas.webp",
      display_order: 2,
    },
    {
      name: "Helado de Vainilla Artesanal",
      description: "Helado cremoso de vainilla hecho con yemas, crema y vainilla natural. Base para postres y servicio directo.",
      ingredients: ["Crema para batir", "Leche entera", "Yemas de huevo", "Azúcar", "Vainilla"],
      prep_time: "45 min + 4 hrs congelado",
      servings: "1 litro",
      image_url: "/images/recipes/helado-vainilla.webp",
      display_order: 3,
    },
    {
      name: "Flan Napolitano",
      description: "Postre cremoso de huevo y leche condensada bañado en caramelo. Un clásico infalible.",
      ingredients: ["Leche condensada", "Leche evaporada", "Huevo fresco", "Azúcar", "Vainilla"],
      prep_time: "1 hr + 4 hrs refrigeración",
      servings: "8 porciones",
      image_url: "/images/recipes/flan-napolitano.webp",
      display_order: 4,
    },
    {
      name: "Pay de Limón",
      description: "Base de galleta con relleno cremoso de limón y cobertura de merengue o crema batida.",
      ingredients: ["Galletas Marías", "Mantequilla", "Leche condensada", "Limón agrio", "Crema para batir"],
      prep_time: "40 min + 3 hrs refrigeración",
      servings: "8 rebanadas",
      image_url: "/images/recipes/pay-limon.webp",
      display_order: 5,
    },
    {
      name: "Churros con Cajeta",
      description: "Churros crujientes espolvoreados con azúcar y canela, servidos con cajeta caliente.",
      ingredients: ["Harina de trigo", "Mantequilla", "Huevo fresco", "Azúcar", "Canela en polvo", "Cajeta", "Aceite vegetal"],
      prep_time: "30 min",
      servings: "20 churros",
      image_url: "/images/recipes/churros-cajeta.webp",
      display_order: 6,
    },
  ],

  // ── 12. Comida Árabe / Griega ─────────────────────
  "comida-arabe-griega": [
    {
      name: "Shawarma de Pollo",
      description: "Tiras de pollo marinado en especias árabes, servido en pan pita con jocoque y verduras.",
      ingredients: ["Pechuga de pollo", "Pan pita", "Jocoque", "Pepino", "Jitomate bola", "Cebolla morada", "Comino", "Pimentón"],
      prep_time: "40 min",
      servings: "6 shawarmas",
      image_url: "/images/recipes/shawarma-pollo.webp",
      display_order: 1,
    },
    {
      name: "Gyro de Cerdo",
      description: "Carne de cerdo marinada con hierbas griegas, servida en pan pita con tzatziki y vegetales.",
      ingredients: ["Pierna de cerdo", "Pan pita", "Yogur griego", "Pepino", "Ajo", "Eneldo", "Limón agrio", "Aceite de oliva"],
      prep_time: "1 hr",
      servings: "6 gyros",
      image_url: "/images/recipes/gyro-cerdo.webp",
      display_order: 2,
    },
    {
      name: "Hummus Casero",
      description: "Crema de garbanzo con tahini, limón y ajo. Entrada o acompañamiento esencial de la cocina árabe.",
      ingredients: ["Garbanzo", "Tahini", "Limón agrio", "Ajo", "Aceite de oliva", "Pimentón", "Pan pita"],
      prep_time: "15 min",
      servings: "8 porciones",
      image_url: "/images/recipes/hummus.webp",
      display_order: 3,
    },
    {
      name: "Falafel Frito",
      description: "Bolitas de garbanzo especiado, fritas y crujientes, servidas en pan pita con salsa tahini.",
      ingredients: ["Garbanzo", "Cilantro fresco", "Comino", "Ajo", "Pan pita", "Tahini", "Aceite vegetal"],
      prep_time: "40 min",
      servings: "20 piezas",
      image_url: "/images/recipes/falafel.webp",
      display_order: 4,
    },
    {
      name: "Ensalada Griega",
      description: "Jitomate, pepino, cebolla morada, aceituna kalamata y queso feta con aceite de oliva.",
      ingredients: ["Jitomate bola", "Pepino", "Cebolla morada", "Aceituna kalamata", "Queso feta", "Aceite de oliva", "Orégano"],
      prep_time: "15 min",
      servings: "4 porciones",
      image_url: "/images/recipes/ensalada-griega.webp",
      display_order: 5,
    },
    {
      name: "Baklava",
      description: "Postre de capas de pasta filo con nuez picada, bañado en miel y jarabe de azúcar.",
      ingredients: ["Pasta filo", "Nuez de castilla", "Pistache", "Mantequilla", "Miel de abeja", "Azúcar", "Canela en polvo"],
      prep_time: "1 hr",
      servings: "16 piezas",
      image_url: "/images/recipes/baklava.webp",
      display_order: 6,
    },
  ],

  // ── 13. Comida Venezolana / Latina ─────────────────
  "comida-venezolana-latina": [
    {
      name: "Arepas Reina Pepiada",
      description: "Arepa de harina PAN rellena de pollo deshebrado con aguacate y mayonesa. El ícono venezolano.",
      ingredients: ["Harina PAN", "Pechuga de pollo", "Aguacate hass", "Mayonesa", "Cebolla blanca", "Cilantro fresco", "Limón agrio"],
      prep_time: "40 min",
      servings: "6 arepas",
      image_url: "/images/recipes/arepas.webp",
      display_order: 1,
    },
    {
      name: "Patacones",
      description: "Plátano macho verde frito, aplanado y vuelto a freír. Base crujiente para acompañar cualquier plato.",
      ingredients: ["Plátano macho", "Aceite vegetal", "Sal", "Ajo en polvo"],
      prep_time: "20 min",
      servings: "4 porciones",
      image_url: "/images/recipes/patacones.webp",
      display_order: 2,
    },
    {
      name: "Empanadas Colombianas",
      description: "Empanadas de maíz rellenas de carne y papa con ají picante.",
      ingredients: ["Harina de maíz precocida", "Carne molida 80/20", "Papas blancas", "Cebolla blanca", "Comino", "Achiote", "Aceite vegetal"],
      prep_time: "50 min",
      servings: "12 empanadas",
      image_url: "/images/recipes/empanadas-colombianas.webp",
      display_order: 3,
    },
    {
      name: "Cachapas con Queso",
      description: "Tortitas dulces de maíz tierno rellenas de queso de mano. Especialidad venezolana.",
      ingredients: ["Maíz tierno", "Queso de mano", "Leche entera", "Azúcar", "Mantequilla"],
      prep_time: "25 min",
      servings: "6 cachapas",
      image_url: "/images/recipes/cachapas.webp",
      display_order: 4,
    },
    {
      name: "Tequeños",
      description: "Palitos de masa rellenos de queso, fritos hasta dorar. Botana venezolana infaltable.",
      ingredients: ["Harina de trigo", "Queso blanco", "Huevo fresco", "Aceite vegetal"],
      prep_time: "40 min",
      servings: "24 piezas",
      image_url: "/images/recipes/tequenos.webp",
      display_order: 5,
    },
    {
      name: "Bandeja Paisa",
      description: "Plato colombiano con frijoles, arroz, carne molida, chicharrón, huevo y plátano maduro.",
      ingredients: ["Frijoles rojos", "Arroz blanco", "Carne molida 80/20", "Chicharrón", "Huevo fresco", "Plátano macho", "Aguacate hass"],
      prep_time: "1.5 hrs",
      servings: "4 porciones",
      image_url: "/images/recipes/bandeja-paisa.webp",
      display_order: 6,
    },
  ],

  // ── 14. Bebidas, Bares y Botanas ───────────────────
  "bebidas-bares-botanas": [
    {
      name: "Michelada Clásica",
      description: "Cerveza con jugo de limón, salsa inglesa, salsa picante y sal en escarcha. La reina de las botanas.",
      ingredients: ["Cerveza clara", "Limón agrio", "Salsa inglesa", "Salsa picante", "Sal", "Hielo", "Chile en polvo"],
      prep_time: "5 min",
      servings: "1 michelada",
      image_url: "/images/recipes/michelada.webp",
      display_order: 1,
    },
    {
      name: "Nachos Supreme",
      description: "Totopos con queso fundido, carne, jalapeños, crema y guacamole. El rey de las botanas.",
      ingredients: ["Totopos", "Queso cheddar rebanado", "Carne molida 80/20", "Jalapeños en escabeche", "Crema ácida", "Aguacate hass", "Jitomate saladet"],
      prep_time: "20 min",
      servings: "6 porciones",
      image_url: "/images/recipes/nachos.webp",
      display_order: 2,
    },
    {
      name: "Limonada Natural",
      description: "Jugo de limón fresco con azúcar y agua mineral. Refrescante y natural.",
      ingredients: ["Limón agrio", "Azúcar", "Agua mineral", "Hielo", "Hierbabuena fresca"],
      prep_time: "10 min",
      servings: "2 litros",
      image_url: "/images/recipes/limonada.webp",
      display_order: 3,
    },
    {
      name: "Margarita Clásica",
      description: "Tequila, licor de naranja y jugo de limón con escarcha de sal. El cóctel mexicano por excelencia.",
      ingredients: ["Tequila blanco", "Licor de naranja", "Limón agrio", "Sal", "Hielo"],
      prep_time: "5 min",
      servings: "1 margarita",
      image_url: "/images/recipes/margarita.webp",
      display_order: 4,
    },
    {
      name: "Guacamole Tradicional",
      description: "Aguacate machacado con jitomate, cebolla, cilantro y chile serrano. Acompañamiento clásico.",
      ingredients: ["Aguacate hass", "Jitomate saladet", "Cebolla blanca", "Cilantro fresco", "Chile serrano", "Limón agrio", "Sal"],
      prep_time: "15 min",
      servings: "6 porciones",
      image_url: "/images/recipes/guacamole.webp",
      display_order: 5,
    },
    {
      name: "Mojito Cubano",
      description: "Ron blanco con hierbabuena, limón, azúcar y agua mineral. Refrescante clásico caribeño.",
      ingredients: ["Ron blanco", "Hierbabuena fresca", "Limón agrio", "Azúcar", "Agua mineral", "Hielo"],
      prep_time: "10 min",
      servings: "1 mojito",
      image_url: "/images/recipes/mojito.webp",
      display_order: 6,
    },
  ],
}

/**
 * Obtiene las recetas para una colección específica.
 */
export function getCollectionRecipes(collectionSlug: string): RecipeInput[] {
  return RECIPES[collectionSlug] || []
}

/**
 * Obtiene todas las recetas agrupadas por colección.
 */
export function getAllRecipes(): Record<string, RecipeInput[]> {
  return RECIPES
}
