-- Migration: Corrige URLs de imagen de productos hacia WebP local / imágenes reales.
-- Reemplaza URLs rotas (paginas resurte.me/es/p y .png inexistentes) por imágenes válidas.
-- Generado a partir de src/app/api/admin/update-images/route.ts (IMAGE_UPDATES + MULTI_IMAGES).

UPDATE products SET image_url = 'https://storage.googleapis.com/takeapp/media/cmihp02pp000604l43fzq2ed7.png', images = jsonb_build_array('https://storage.googleapis.com/takeapp/media/cmihp02pp000604l43fzq2ed7.png', 'https://storage.googleapis.com/takeapp/media/cmihp1d5p000904l4ap1f6tf8.png', 'https://storage.googleapis.com/takeapp/media/cmihojint000k04if2qg48em7.png'), updated_at = now() WHERE id = 1;
UPDATE products SET image_url = 'https://storage.googleapis.com/takeapp/media/cmihov9fh001304ju8yfi21dq.png', images = jsonb_build_array('https://storage.googleapis.com/takeapp/media/cmihov9fh001304ju8yfi21dq.png', 'https://storage.googleapis.com/takeapp/media/cmihounrr001004ju2zr0kkrr.png'), updated_at = now() WHERE id = 2;
UPDATE products SET image_url = 'https://storage.googleapis.com/takeapp/media/cmihon5gm000f04jo8q5f7jdf.png', images = jsonb_build_array('https://storage.googleapis.com/takeapp/media/cmihon5gm000f04jo8q5f7jdf.png', 'https://storage.googleapis.com/takeapp/media/cmihqf2pi000704la16zb486c.png'), updated_at = now() WHERE id = 3;
UPDATE products SET image_url = 'https://storage.googleapis.com/takeapp/media/cmijnpm2z000904lbg1e59xve.png', images = jsonb_build_array('https://storage.googleapis.com/takeapp/media/cmijnpm2z000904lbg1e59xve.png', 'https://storage.googleapis.com/takeapp/media/cmijnpqc1000c04lb4mr4b1cy.png'), updated_at = now() WHERE id = 4;
UPDATE products SET image_url = 'https://storage.googleapis.com/takeapp/media/cmijp7zpj000404l40mtkbyuh.png', images = jsonb_build_array('https://storage.googleapis.com/takeapp/media/cmijp7zpj000404l40mtkbyuh.png', 'https://storage.googleapis.com/takeapp/media/cmijp8bq3000604le988t96v6.png'), updated_at = now() WHERE id = 5;
UPDATE products SET image_url = 'https://storage.googleapis.com/takeapp/media/cmijo779j000204jz2yrwe753.png', images = jsonb_build_array('https://storage.googleapis.com/takeapp/media/cmijo779j000204jz2yrwe753.png', 'https://storage.googleapis.com/takeapp/media/cmijo7k5s000504jzcz7ye4bg.png'), updated_at = now() WHERE id = 6;
UPDATE products SET image_url = '/images/products/7.webp', images = jsonb_build_array('/images/products/7.webp'), updated_at = now() WHERE id = 7;
UPDATE products SET image_url = '/images/products/8.webp', images = jsonb_build_array('/images/products/8.webp'), updated_at = now() WHERE id = 8;
UPDATE products SET image_url = 'https://storage.googleapis.com/takeapp/media/cmijostxx001o04jv3tl8b2v9.png', images = jsonb_build_array('https://storage.googleapis.com/takeapp/media/cmijostxx001o04jv3tl8b2v9.png', 'https://storage.googleapis.com/takeapp/media/cmijosl2y001l04jvck78hm6m.png'), updated_at = now() WHERE id = 9;
UPDATE products SET image_url = '/images/products/10.webp', images = jsonb_build_array('/images/products/10.webp'), updated_at = now() WHERE id = 10;
UPDATE products SET image_url = 'https://storage.googleapis.com/takeapp/media/cmijwgf7r000904l738kc1xwb.png', images = jsonb_build_array('https://storage.googleapis.com/takeapp/media/cmijwgf7r000904l738kc1xwb.png', 'https://storage.googleapis.com/takeapp/media/cmijwgwcq000b04l7bh364jb2.png'), updated_at = now() WHERE id = 11;
UPDATE products SET image_url = 'https://storage.googleapis.com/takeapp/media/cmijq38em001604l7hja83595.png', images = jsonb_build_array('https://storage.googleapis.com/takeapp/media/cmijq38em001604l7hja83595.png', 'https://storage.googleapis.com/takeapp/media/cmijq3jh4001904l7b5ua1tia.png'), updated_at = now() WHERE id = 12;
UPDATE products SET image_url = 'https://storage.googleapis.com/takeapp/media/cmijy9mol000104jr05q555i9.png', images = jsonb_build_array('https://storage.googleapis.com/takeapp/media/cmijy9mol000104jr05q555i9.png', 'https://storage.googleapis.com/takeapp/media/cmijy9y2d000304jr51oz2wx0.png'), updated_at = now() WHERE id = 13;
UPDATE products SET image_url = 'https://storage.googleapis.com/takeapp/media/cmijt78vd000304l7gky09s9z.png', images = jsonb_build_array('https://storage.googleapis.com/takeapp/media/cmijt78vd000304l7gky09s9z.png', 'https://storage.googleapis.com/takeapp/media/cmijt7m3w000504l725d40nzv.png'), updated_at = now() WHERE id = 14;
UPDATE products SET image_url = 'https://storage.googleapis.com/takeapp/media/cmil8aa8y001b04jodgx5fcbu.png', images = jsonb_build_array('https://storage.googleapis.com/takeapp/media/cmil8aa8y001b04jodgx5fcbu.png', 'https://storage.googleapis.com/takeapp/media/cmil8af9n001d04jo0tnf2y5m.png'), updated_at = now() WHERE id = 15;
UPDATE products SET image_url = 'https://storage.googleapis.com/takeapp/media/cmikmo2xq000304l8d0pmawqd.png', images = jsonb_build_array('https://storage.googleapis.com/takeapp/media/cmikmo2xq000304l8d0pmawqd.png', 'https://storage.googleapis.com/takeapp/media/cmikmmodl000504l84zeleisj.png'), updated_at = now() WHERE id = 16;
UPDATE products SET image_url = 'https://storage.googleapis.com/takeapp/media/cmikmw51n000304jz0r6shapj.png', images = jsonb_build_array('https://storage.googleapis.com/takeapp/media/cmikmw51n000304jz0r6shapj.png', 'https://storage.googleapis.com/takeapp/media/cmikmx0wp000504jz4j5x1ij2.png'), updated_at = now() WHERE id = 17;
UPDATE products SET image_url = 'https://storage.googleapis.com/takeapp/media/cmijqtay4000604js048vejxu.png', images = jsonb_build_array('https://storage.googleapis.com/takeapp/media/cmijqtay4000604js048vejxu.png', 'https://storage.googleapis.com/takeapp/media/cmijqtnm5000904jsc56c3o9n.png'), updated_at = now() WHERE id = 18;
UPDATE products SET image_url = 'https://storage.googleapis.com/takeapp/media/cmijtu4fq000204jy1h4p53xa.png', images = jsonb_build_array('https://storage.googleapis.com/takeapp/media/cmijtu4fq000204jy1h4p53xa.png', 'https://storage.googleapis.com/takeapp/media/cmijtugir000404jyckcs1xx4.png'), updated_at = now() WHERE id = 19;
UPDATE products SET image_url = 'https://storage.googleapis.com/takeapp/media/cmihqyxja000b04l5h1s4euob.png', images = jsonb_build_array('https://storage.googleapis.com/takeapp/media/cmihqyxja000b04l5h1s4euob.png', 'https://storage.googleapis.com/takeapp/media/cmihqz0u3000e04l53hps6u71.png'), updated_at = now() WHERE id = 20;
UPDATE products SET image_url = 'https://storage.googleapis.com/takeapp/media/cmijjlfbn000504ie32jadi6o.png', images = jsonb_build_array('https://storage.googleapis.com/takeapp/media/cmijjlfbn000504ie32jadi6o.png', 'https://storage.googleapis.com/takeapp/media/cmijjlv27000804ie5n33c2ci.png'), updated_at = now() WHERE id = 21;
UPDATE products SET image_url = 'https://storage.googleapis.com/takeapp/media/cmigud8dq000n04jp1kc96rqk.png', images = jsonb_build_array('https://storage.googleapis.com/takeapp/media/cmigud8dq000n04jp1kc96rqk.png', 'https://storage.googleapis.com/takeapp/media/cmigudi7w000q04jpbzr8whtc.png'), updated_at = now() WHERE id = 22;
UPDATE products SET image_url = 'https://storage.googleapis.com/takeapp/media/cmihm7h13000104jsc7rz709l.png', images = jsonb_build_array('https://storage.googleapis.com/takeapp/media/cmihm7h13000104jsc7rz709l.png', 'https://storage.googleapis.com/takeapp/media/cmihm7q5r000404js0ghz1e8d.png'), updated_at = now() WHERE id = 23;
UPDATE products SET image_url = 'https://storage.googleapis.com/takeapp/media/cmihm9eva000804kwbbsuf58x.png', images = jsonb_build_array('https://storage.googleapis.com/takeapp/media/cmihm9eva000804kwbbsuf58x.png', 'https://storage.googleapis.com/takeapp/media/cmihm9ngw000a04kwb2m6gm6h.png'), updated_at = now() WHERE id = 24;
UPDATE products SET image_url = 'https://storage.googleapis.com/takeapp/media/cmifgtjlp000b04l5a5r89mmc.jpg', images = jsonb_build_array('https://storage.googleapis.com/takeapp/media/cmifgtjlp000b04l5a5r89mmc.jpg', 'https://storage.googleapis.com/takeapp/media/cmifgtpke000e04l528or02g3.jpg'), updated_at = now() WHERE id = 25;
UPDATE products SET image_url = 'https://storage.googleapis.com/takeapp/media/cmil9723z002s04jobceb395t.png', images = jsonb_build_array('https://storage.googleapis.com/takeapp/media/cmil9723z002s04jobceb395t.png', 'https://storage.googleapis.com/takeapp/media/cmil97bow002u04jodau3fs80.png'), updated_at = now() WHERE id = 26;
UPDATE products SET image_url = 'https://storage.googleapis.com/takeapp/media/cmigh1lun000104lfbmdi5wgm.jpg', images = jsonb_build_array('https://storage.googleapis.com/takeapp/media/cmigh1lun000104lfbmdi5wgm.jpg', 'https://storage.googleapis.com/takeapp/media/cmigh1r3n000404lfbkx14tun.jpg'), updated_at = now() WHERE id = 27;
UPDATE products SET image_url = 'https://storage.googleapis.com/takeapp/media/cmihn1bq8000604l53jdqdh3t.png', images = jsonb_build_array('https://storage.googleapis.com/takeapp/media/cmihn1bq8000604l53jdqdh3t.png', 'https://storage.googleapis.com/takeapp/media/cmihn1kft000804l5af676n3h.png'), updated_at = now() WHERE id = 28;
UPDATE products SET image_url = 'https://storage.googleapis.com/takeapp/media/cmihlx4ko000004jp6pn34jcc.png', images = jsonb_build_array('https://storage.googleapis.com/takeapp/media/cmihlx4ko000004jp6pn34jcc.png', 'https://storage.googleapis.com/takeapp/media/cmihlxd3u000204jp0dyt3thh.png'), updated_at = now() WHERE id = 29;
UPDATE products SET image_url = 'https://storage.googleapis.com/takeapp/media/cmiguf9xj000c04ih2kpi7szc.png', images = jsonb_build_array('https://storage.googleapis.com/takeapp/media/cmiguf9xj000c04ih2kpi7szc.png', 'https://storage.googleapis.com/takeapp/media/cmiguffd8000f04ih1vbr4cub.png'), updated_at = now() WHERE id = 30;
UPDATE products SET image_url = 'https://storage.googleapis.com/takeapp/media/cmihgsazp000204ib1z4gae1g.png', images = jsonb_build_array('https://storage.googleapis.com/takeapp/media/cmihgsazp000204ib1z4gae1g.png', 'https://storage.googleapis.com/takeapp/media/cmihgsgtn000404ib09b78qrm.png'), updated_at = now() WHERE id = 31;
UPDATE products SET image_url = 'https://storage.googleapis.com/takeapp/media/cmilwesph000704ikfang4orw.png', images = jsonb_build_array('https://storage.googleapis.com/takeapp/media/cmilwesph000704ikfang4orw.png', 'https://storage.googleapis.com/takeapp/media/cmilwexvb000904ikc5ov3ffv.png'), updated_at = now() WHERE id = 32;
UPDATE products SET image_url = 'https://storage.googleapis.com/takeapp/media/cmilw6t51000104jq0du3blee.png', images = jsonb_build_array('https://storage.googleapis.com/takeapp/media/cmilw6t51000104jq0du3blee.png', 'https://storage.googleapis.com/takeapp/media/cmilw6kb5000204l8hoc09tg9.png'), updated_at = now() WHERE id = 33;
UPDATE products SET image_url = '/images/products/34.webp', images = jsonb_build_array('/images/products/34.webp'), updated_at = now() WHERE id = 34;
UPDATE products SET image_url = 'https://storage.googleapis.com/takeapp/media/cmikw8rii000104l7e1vfbfw3.png', images = jsonb_build_array('https://storage.googleapis.com/takeapp/media/cmikw8rii000104l7e1vfbfw3.png', 'https://storage.googleapis.com/takeapp/media/cmikw8wms000304l770o1crl9.png'), updated_at = now() WHERE id = 35;
UPDATE products SET image_url = 'https://storage.googleapis.com/takeapp/media/cmijm5teg000704lbgiuf2ua2.png', images = jsonb_build_array('https://storage.googleapis.com/takeapp/media/cmijm5teg000704lbgiuf2ua2.png', 'https://storage.googleapis.com/takeapp/media/cmijm5z1p000a04lb72yr2qyn.png'), updated_at = now() WHERE id = 36;
UPDATE products SET image_url = 'https://storage.googleapis.com/takeapp/media/cmikz37kb000004l5d2653hrg.png', images = jsonb_build_array('https://storage.googleapis.com/takeapp/media/cmikz37kb000004l5d2653hrg.png', 'https://storage.googleapis.com/takeapp/media/cmikz3md8000204l54oh20h6s.png'), updated_at = now() WHERE id = 37;
UPDATE products SET image_url = 'https://storage.googleapis.com/takeapp/media/cmihqf2pi000704la16zb486c.png', images = jsonb_build_array('https://storage.googleapis.com/takeapp/media/cmihqf2pi000704la16zb486c.png', 'https://storage.googleapis.com/takeapp/media/cmihqf9ew000904la3nwxdp0q.png'), updated_at = now() WHERE id = 38;
UPDATE products SET image_url = 'https://storage.googleapis.com/takeapp/media/cmij91iox000804l6hp3j6ul8.png', images = jsonb_build_array('https://storage.googleapis.com/takeapp/media/cmij91iox000804l6hp3j6ul8.png', 'https://storage.googleapis.com/takeapp/media/cmij91w15000b04l6g9h4gv4r.png'), updated_at = now() WHERE id = 39;
UPDATE products SET image_url = 'https://storage.googleapis.com/takeapp/media/cmijj1878000004k0bji0clqu.png', images = jsonb_build_array('https://storage.googleapis.com/takeapp/media/cmijj1878000004k0bji0clqu.png', 'https://storage.googleapis.com/takeapp/media/cmijj1l50000304k008lw8aq9.png'), updated_at = now() WHERE id = 40;
UPDATE products SET image_url = 'https://storage.googleapis.com/takeapp/media/cmijn2j9r000304js6krldwj1.png', images = jsonb_build_array('https://storage.googleapis.com/takeapp/media/cmijn2j9r000304js6krldwj1.png', 'https://storage.googleapis.com/takeapp/media/cmijn2q1z000504js2024s5m50.png'), updated_at = now() WHERE id = 41;
UPDATE products SET image_url = 'https://storage.googleapis.com/takeapp/media/cmihhifyb000004jv1j7x5wbp.png', images = jsonb_build_array('https://storage.googleapis.com/takeapp/media/cmihhifyb000004jv1j7x5wbp.png', 'https://storage.googleapis.com/takeapp/media/cmihhiwpn000304jv4pgf7m7s.png'), updated_at = now() WHERE id = 42;
UPDATE products SET image_url = 'https://storage.googleapis.com/takeapp/media/cmigufsl3000604l59l4of2yy.png', images = jsonb_build_array('https://storage.googleapis.com/takeapp/media/cmigufsl3000604l59l4of2yy.png', 'https://storage.googleapis.com/takeapp/media/cmigufy68000804ihcy69c2n4.png'), updated_at = now() WHERE id = 43;
UPDATE products SET image_url = 'https://storage.googleapis.com/takeapp/media/cmijmdkue000004l5cl6t57qd.png', images = jsonb_build_array('https://storage.googleapis.com/takeapp/media/cmijmdkue000004l5cl6t57qd.png', 'https://storage.googleapis.com/takeapp/media/cmijmdtxh000204l57eu05o4q.png'), updated_at = now() WHERE id = 44;
UPDATE products SET image_url = 'https://storage.googleapis.com/takeapp/media/cmikm2eyl000g04l9h841dwam.png', images = jsonb_build_array('https://storage.googleapis.com/takeapp/media/cmikm2eyl000g04l9h841dwam.png', 'https://storage.googleapis.com/takeapp/media/cmikm2kyk000i04l99v5y5ag8.png'), updated_at = now() WHERE id = 45;
UPDATE products SET image_url = 'https://storage.googleapis.com/takeapp/media/cmihhsrrr000004jfc58l4cxz.png', images = jsonb_build_array('https://storage.googleapis.com/takeapp/media/cmihhsrrr000004jfc58l4cxz.png', 'https://storage.googleapis.com/takeapp/media/cmihht171000304jfh2lzc04d.png'), updated_at = now() WHERE id = 46;
UPDATE products SET image_url = 'https://storage.googleapis.com/takeapp/media/cmigr3lni000004l281j40gvp.jpg', images = jsonb_build_array('https://storage.googleapis.com/takeapp/media/cmigr3lni000004l281j40gvp.jpg', 'https://storage.googleapis.com/takeapp/media/cmigr3r7s000304l22p3r4fx5.jpg', 'https://storage.googleapis.com/takeapp/media/cmigujm9f000204lk0jfhc8ha.png'), updated_at = now() WHERE id = 47;
UPDATE products SET image_url = 'https://storage.googleapis.com/takeapp/media/cmifh7a6k000004jpa7or85li.jpg', images = jsonb_build_array('https://storage.googleapis.com/takeapp/media/cmifh7a6k000004jpa7or85li.jpg', 'https://storage.googleapis.com/takeapp/media/cmifh7dx3000304jpaymq66n4.jpg'), updated_at = now() WHERE id = 48;
UPDATE products SET image_url = '/images/products/49.webp', images = jsonb_build_array('/images/products/49.webp'), updated_at = now() WHERE id = 49;
UPDATE products SET image_url = '/images/products/50.webp', images = jsonb_build_array('/images/products/50.webp'), updated_at = now() WHERE id = 50;
UPDATE products SET image_url = '/images/products/51.webp', images = jsonb_build_array('/images/products/51.webp'), updated_at = now() WHERE id = 51;
UPDATE products SET image_url = '/images/products/52.webp', images = jsonb_build_array('/images/products/52.webp'), updated_at = now() WHERE id = 52;
UPDATE products SET image_url = '/images/products/53.webp', images = jsonb_build_array('/images/products/53.webp'), updated_at = now() WHERE id = 53;
UPDATE products SET image_url = '/images/products/54.webp', images = jsonb_build_array('/images/products/54.webp'), updated_at = now() WHERE id = 54;
UPDATE products SET image_url = '/images/products/55.webp', images = jsonb_build_array('/images/products/55.webp'), updated_at = now() WHERE id = 55;
UPDATE products SET image_url = '/images/products/56.webp', images = jsonb_build_array('/images/products/56.webp'), updated_at = now() WHERE id = 56;
UPDATE products SET image_url = '/images/products/57.webp', images = jsonb_build_array('/images/products/57.webp'), updated_at = now() WHERE id = 57;
UPDATE products SET image_url = '/images/products/59.webp', images = jsonb_build_array('/images/products/59.webp'), updated_at = now() WHERE id = 59;
UPDATE products SET image_url = '/images/products/60.webp', images = jsonb_build_array('/images/products/60.webp'), updated_at = now() WHERE id = 60;
UPDATE products SET image_url = '/images/products/61.webp', images = jsonb_build_array('/images/products/61.webp'), updated_at = now() WHERE id = 61;
UPDATE products SET image_url = '/images/products/64.webp', images = jsonb_build_array('/images/products/64.webp'), updated_at = now() WHERE id = 64;
UPDATE products SET image_url = '/images/products/68.webp', images = jsonb_build_array('/images/products/68.webp'), updated_at = now() WHERE id = 68;
UPDATE products SET image_url = '/images/products/71.webp', images = jsonb_build_array('/images/products/71.webp'), updated_at = now() WHERE id = 71;
UPDATE products SET image_url = '/images/products/72.webp', images = jsonb_build_array('/images/products/72.webp'), updated_at = now() WHERE id = 72;
UPDATE products SET image_url = '/images/products/75.webp', images = jsonb_build_array('/images/products/75.webp'), updated_at = now() WHERE id = 75;
UPDATE products SET image_url = '/images/products/77.webp', images = jsonb_build_array('/images/products/77.webp'), updated_at = now() WHERE id = 77;
UPDATE products SET image_url = '/images/products/80.webp', images = jsonb_build_array('/images/products/80.webp'), updated_at = now() WHERE id = 80;
UPDATE products SET image_url = '/images/products/81.webp', images = jsonb_build_array('/images/products/81.webp'), updated_at = now() WHERE id = 81;
UPDATE products SET image_url = '/images/products/83.webp', images = jsonb_build_array('/images/products/83.webp'), updated_at = now() WHERE id = 83;
UPDATE products SET image_url = '/images/products/85.webp', images = jsonb_build_array('/images/products/85.webp'), updated_at = now() WHERE id = 85;
UPDATE products SET image_url = 'https://storage.googleapis.com/takeapp/media/cmidk5jyk00000icpgw3gh4pc.webp', images = jsonb_build_array('https://storage.googleapis.com/takeapp/media/cmidk5jyk00000icpgw3gh4pc.webp'), updated_at = now() WHERE id = 89;
UPDATE products SET image_url = '/images/products/90.webp', images = jsonb_build_array('/images/products/90.webp'), updated_at = now() WHERE id = 90;
UPDATE products SET image_url = '/images/products/91.webp', images = jsonb_build_array('/images/products/91.webp'), updated_at = now() WHERE id = 91;
UPDATE products SET image_url = '/images/products/92.webp', images = jsonb_build_array('/images/products/92.webp'), updated_at = now() WHERE id = 92;
UPDATE products SET image_url = '/images/products/93.webp', images = jsonb_build_array('/images/products/93.webp'), updated_at = now() WHERE id = 93;
UPDATE products SET image_url = 'https://storage.googleapis.com/takeapp/media/cmidk59fi00000imqacaggoal.webp', images = jsonb_build_array('https://storage.googleapis.com/takeapp/media/cmidk59fi00000imqacaggoal.webp'), updated_at = now() WHERE id = 94;
UPDATE products SET image_url = 'https://storage.googleapis.com/takeapp/media/cmidk59fi00000imqacaggoal.webp', images = jsonb_build_array('https://storage.googleapis.com/takeapp/media/cmidk59fi00000imqacaggoal.webp'), updated_at = now() WHERE id = 95;
UPDATE products SET image_url = '/images/products/96.webp', images = jsonb_build_array('/images/products/96.webp'), updated_at = now() WHERE id = 96;
UPDATE products SET image_url = '/images/products/97.webp', images = jsonb_build_array('/images/products/97.webp'), updated_at = now() WHERE id = 97;
UPDATE products SET image_url = '/images/products/98.webp', images = jsonb_build_array('/images/products/98.webp'), updated_at = now() WHERE id = 98;
UPDATE products SET image_url = '/images/products/99.webp', images = jsonb_build_array('/images/products/99.webp'), updated_at = now() WHERE id = 99;
UPDATE products SET image_url = '/images/products/100.webp', images = jsonb_build_array('/images/products/100.webp'), updated_at = now() WHERE id = 100;
UPDATE products SET image_url = 'https://storage.googleapis.com/takeapp/media/cmidk5taj00000igwdgi364t0.webp', images = jsonb_build_array('https://storage.googleapis.com/takeapp/media/cmidk5taj00000igwdgi364t0.webp'), updated_at = now() WHERE id = 101;
UPDATE products SET image_url = '/images/products/102.webp', images = jsonb_build_array('/images/products/102.webp'), updated_at = now() WHERE id = 102;
UPDATE products SET image_url = 'https://storage.googleapis.com/takeapp/media/cmidk5ahb00000ikx1fo4ebab.webp', images = jsonb_build_array('https://storage.googleapis.com/takeapp/media/cmidk5ahb00000ikx1fo4ebab.webp'), updated_at = now() WHERE id = 103;
UPDATE products SET image_url = 'https://storage.googleapis.com/takeapp/media/cmidk5ucg00000ijff55kb0k6.webp', images = jsonb_build_array('https://storage.googleapis.com/takeapp/media/cmidk5ucg00000ijff55kb0k6.webp', 'https://storage.googleapis.com/takeapp/media/cmidk60e200030ijffg7mmfo2z.webp'), updated_at = now() WHERE id = 104;
UPDATE products SET image_url = '/images/products/105.webp', images = jsonb_build_array('/images/products/105.webp'), updated_at = now() WHERE id = 105;
UPDATE products SET image_url = '/images/products/106.webp', images = jsonb_build_array('/images/products/106.webp'), updated_at = now() WHERE id = 106;
UPDATE products SET image_url = '/images/products/107.webp', images = jsonb_build_array('/images/products/107.webp'), updated_at = now() WHERE id = 107;
UPDATE products SET image_url = '/images/products/108.webp', images = jsonb_build_array('/images/products/108.webp'), updated_at = now() WHERE id = 108;
UPDATE products SET image_url = '/images/products/111.webp', images = jsonb_build_array('/images/products/111.webp'), updated_at = now() WHERE id = 111;
UPDATE products SET image_url = '/images/products/112.webp', images = jsonb_build_array('/images/products/112.webp'), updated_at = now() WHERE id = 112;
UPDATE products SET image_url = '/images/products/113.webp', images = jsonb_build_array('/images/products/113.webp'), updated_at = now() WHERE id = 113;
UPDATE products SET image_url = 'https://storage.googleapis.com/takeapp/media/cmigudmvx000p04jp7knq43u4.png', images = jsonb_build_array('https://storage.googleapis.com/takeapp/media/cmigudmvx000p04jp7knq43u4.png', 'https://storage.googleapis.com/takeapp/media/cmigudrly000s04jpe45e71lo.png'), updated_at = now() WHERE id = 115;
UPDATE products SET image_url = '/images/products/116.webp', images = jsonb_build_array('/images/products/116.webp'), updated_at = now() WHERE id = 116;
UPDATE products SET image_url = '/images/products/117.webp', images = jsonb_build_array('/images/products/117.webp'), updated_at = now() WHERE id = 117;
UPDATE products SET image_url = '/images/products/118.webp', images = jsonb_build_array('/images/products/118.webp'), updated_at = now() WHERE id = 118;
UPDATE products SET image_url = '/images/products/119.webp', images = jsonb_build_array('/images/products/119.webp'), updated_at = now() WHERE id = 119;
UPDATE products SET image_url = '/images/products/120.webp', images = jsonb_build_array('/images/products/120.webp'), updated_at = now() WHERE id = 120;
UPDATE products SET image_url = '/images/products/121.webp', images = jsonb_build_array('/images/products/121.webp'), updated_at = now() WHERE id = 121;
UPDATE products SET image_url = '/images/products/122.webp', images = jsonb_build_array('/images/products/122.webp'), updated_at = now() WHERE id = 122;
UPDATE products SET image_url = '/images/products/123.webp', images = jsonb_build_array('/images/products/123.webp'), updated_at = now() WHERE id = 123;
UPDATE products SET image_url = '/images/products/124.webp', images = jsonb_build_array('/images/products/124.webp'), updated_at = now() WHERE id = 124;
UPDATE products SET image_url = '/images/products/126.webp', images = jsonb_build_array('/images/products/126.webp'), updated_at = now() WHERE id = 126;
UPDATE products SET image_url = '/images/products/127.webp', images = jsonb_build_array('/images/products/127.webp'), updated_at = now() WHERE id = 127;
UPDATE products SET image_url = '/images/products/128.webp', images = jsonb_build_array('/images/products/128.webp'), updated_at = now() WHERE id = 128;
UPDATE products SET image_url = '/images/products/129.webp', images = jsonb_build_array('/images/products/129.webp'), updated_at = now() WHERE id = 129;
UPDATE products SET image_url = '/images/products/130.webp', images = jsonb_build_array('/images/products/130.webp'), updated_at = now() WHERE id = 130;
UPDATE products SET image_url = '/images/products/131.webp', images = jsonb_build_array('/images/products/131.webp'), updated_at = now() WHERE id = 131;
UPDATE products SET image_url = '/images/products/132.webp', images = jsonb_build_array('/images/products/132.webp'), updated_at = now() WHERE id = 132;
UPDATE products SET image_url = '/images/products/133.webp', images = jsonb_build_array('/images/products/133.webp'), updated_at = now() WHERE id = 133;
UPDATE products SET image_url = '/images/products/134.webp', images = jsonb_build_array('/images/products/134.webp'), updated_at = now() WHERE id = 134;
UPDATE products SET image_url = '/images/products/137.webp', images = jsonb_build_array('/images/products/137.webp'), updated_at = now() WHERE id = 137;
UPDATE products SET image_url = '/images/products/138.webp', images = jsonb_build_array('/images/products/138.webp'), updated_at = now() WHERE id = 138;
UPDATE products SET image_url = 'https://storage.googleapis.com/takeapp/media/cmidk5ige00000ij9gnsz26bv.webp', images = jsonb_build_array('https://storage.googleapis.com/takeapp/media/cmidk5ige00000ij9gnsz26bv.webp', 'https://storage.googleapis.com/takeapp/media/cmidk5o07000000hkcn2oeaq4.webp'), updated_at = now() WHERE id = 139;
UPDATE products SET image_url = 'https://storage.googleapis.com/takeapp/media/cmidk5ovr00000hka85jr5bzf.webp', images = jsonb_build_array('https://storage.googleapis.com/takeapp/media/cmidk5ovr00000hka85jr5bzf.webp', 'https://storage.googleapis.com/takeapp/media/cmidk5uvg00000ijcnvka82k1.webp'), updated_at = now() WHERE id = 140;
UPDATE products SET image_url = '/images/products/144.webp', images = jsonb_build_array('/images/products/144.webp'), updated_at = now() WHERE id = 144;
UPDATE products SET image_url = '/images/products/147.webp', images = jsonb_build_array('/images/products/147.webp'), updated_at = now() WHERE id = 147;
UPDATE products SET image_url = '/images/products/149.webp', images = jsonb_build_array('/images/products/149.webp'), updated_at = now() WHERE id = 149;
UPDATE products SET image_url = '/images/products/150.webp', images = jsonb_build_array('/images/products/150.webp'), updated_at = now() WHERE id = 150;
UPDATE products SET image_url = '/images/products/151.webp', images = jsonb_build_array('/images/products/151.webp'), updated_at = now() WHERE id = 151;
UPDATE products SET image_url = '/images/products/152.webp', images = jsonb_build_array('/images/products/152.webp'), updated_at = now() WHERE id = 152;
UPDATE products SET image_url = '/images/products/154.webp', images = jsonb_build_array('/images/products/154.webp'), updated_at = now() WHERE id = 154;
UPDATE products SET image_url = '/images/products/160.webp', images = jsonb_build_array('/images/products/160.webp'), updated_at = now() WHERE id = 160;
UPDATE products SET image_url = '/images/products/162.webp', images = jsonb_build_array('/images/products/162.webp'), updated_at = now() WHERE id = 162;
UPDATE products SET image_url = '/images/products/163.webp', images = jsonb_build_array('/images/products/163.webp'), updated_at = now() WHERE id = 163;
UPDATE products SET image_url = '/images/products/164.webp', images = jsonb_build_array('/images/products/164.webp'), updated_at = now() WHERE id = 164;
UPDATE products SET image_url = '/images/products/169.webp', images = jsonb_build_array('/images/products/169.webp'), updated_at = now() WHERE id = 169;
UPDATE products SET image_url = '/images/products/170.webp', images = jsonb_build_array('/images/products/170.webp'), updated_at = now() WHERE id = 170;
UPDATE products SET image_url = '/images/products/172.webp', images = jsonb_build_array('/images/products/172.webp'), updated_at = now() WHERE id = 172;
UPDATE products SET image_url = '/images/products/173.webp', images = jsonb_build_array('/images/products/173.webp'), updated_at = now() WHERE id = 173;
UPDATE products SET image_url = '/images/products/175.webp', images = jsonb_build_array('/images/products/175.webp'), updated_at = now() WHERE id = 175;
UPDATE products SET image_url = '/images/products/177.webp', images = jsonb_build_array('/images/products/177.webp'), updated_at = now() WHERE id = 177;
UPDATE products SET image_url = '/images/products/178.webp', images = jsonb_build_array('/images/products/178.webp'), updated_at = now() WHERE id = 178;
UPDATE products SET image_url = '/images/products/182.webp', images = jsonb_build_array('/images/products/182.webp'), updated_at = now() WHERE id = 182;
UPDATE products SET image_url = '/images/products/183.webp', images = jsonb_build_array('/images/products/183.webp'), updated_at = now() WHERE id = 183;
UPDATE products SET image_url = '/images/products/184.webp', images = jsonb_build_array('/images/products/184.webp'), updated_at = now() WHERE id = 184;
UPDATE products SET image_url = '/images/products/185.webp', images = jsonb_build_array('/images/products/185.webp'), updated_at = now() WHERE id = 185;
UPDATE products SET image_url = '/images/products/186.webp', images = jsonb_build_array('/images/products/186.webp'), updated_at = now() WHERE id = 186;

-- Productos sin imagen: se marcan no visibles en lugar de borrarse.
UPDATE products SET is_visible = false, updated_at = now() WHERE id = 58;
UPDATE products SET is_visible = false, updated_at = now() WHERE id = 62;
UPDATE products SET is_visible = false, updated_at = now() WHERE id = 63;
UPDATE products SET is_visible = false, updated_at = now() WHERE id = 65;
UPDATE products SET is_visible = false, updated_at = now() WHERE id = 66;
UPDATE products SET is_visible = false, updated_at = now() WHERE id = 67;
UPDATE products SET is_visible = false, updated_at = now() WHERE id = 69;
UPDATE products SET is_visible = false, updated_at = now() WHERE id = 70;
UPDATE products SET is_visible = false, updated_at = now() WHERE id = 73;
UPDATE products SET is_visible = false, updated_at = now() WHERE id = 74;
UPDATE products SET is_visible = false, updated_at = now() WHERE id = 76;
UPDATE products SET is_visible = false, updated_at = now() WHERE id = 78;
UPDATE products SET is_visible = false, updated_at = now() WHERE id = 79;
UPDATE products SET is_visible = false, updated_at = now() WHERE id = 82;
UPDATE products SET is_visible = false, updated_at = now() WHERE id = 84;
UPDATE products SET is_visible = false, updated_at = now() WHERE id = 86;
UPDATE products SET is_visible = false, updated_at = now() WHERE id = 87;
UPDATE products SET is_visible = false, updated_at = now() WHERE id = 88;
UPDATE products SET is_visible = false, updated_at = now() WHERE id = 109;
UPDATE products SET is_visible = false, updated_at = now() WHERE id = 110;
UPDATE products SET is_visible = false, updated_at = now() WHERE id = 114;
UPDATE products SET is_visible = false, updated_at = now() WHERE id = 125;
UPDATE products SET is_visible = false, updated_at = now() WHERE id = 135;
UPDATE products SET is_visible = false, updated_at = now() WHERE id = 136;
UPDATE products SET is_visible = false, updated_at = now() WHERE id = 141;
UPDATE products SET is_visible = false, updated_at = now() WHERE id = 142;
UPDATE products SET is_visible = false, updated_at = now() WHERE id = 143;
UPDATE products SET is_visible = false, updated_at = now() WHERE id = 145;
UPDATE products SET is_visible = false, updated_at = now() WHERE id = 146;
UPDATE products SET is_visible = false, updated_at = now() WHERE id = 148;
UPDATE products SET is_visible = false, updated_at = now() WHERE id = 153;
UPDATE products SET is_visible = false, updated_at = now() WHERE id = 155;
UPDATE products SET is_visible = false, updated_at = now() WHERE id = 156;
UPDATE products SET is_visible = false, updated_at = now() WHERE id = 157;
UPDATE products SET is_visible = false, updated_at = now() WHERE id = 158;
UPDATE products SET is_visible = false, updated_at = now() WHERE id = 159;
UPDATE products SET is_visible = false, updated_at = now() WHERE id = 161;
UPDATE products SET is_visible = false, updated_at = now() WHERE id = 165;
UPDATE products SET is_visible = false, updated_at = now() WHERE id = 166;
UPDATE products SET is_visible = false, updated_at = now() WHERE id = 167;
UPDATE products SET is_visible = false, updated_at = now() WHERE id = 168;
UPDATE products SET is_visible = false, updated_at = now() WHERE id = 171;
UPDATE products SET is_visible = false, updated_at = now() WHERE id = 174;
UPDATE products SET is_visible = false, updated_at = now() WHERE id = 176;
UPDATE products SET is_visible = false, updated_at = now() WHERE id = 179;
UPDATE products SET is_visible = false, updated_at = now() WHERE id = 180;
UPDATE products SET is_visible = false, updated_at = now() WHERE id = 181;
UPDATE products SET is_visible = false, updated_at = now() WHERE id = 187;
