-- ============================================================
-- 00215 — Infografía nutrimental como SEGUNDA imagen de cada producto.
--
-- QUE HACE
-- --------
-- Agrega /images/products/infografia/<slug>.webp como segunda entrada del
-- arreglo `images` de los 268 productos visibles del catálogo, sin
-- tocar `image_url` (la foto principal no cambia). La infografía replica el
-- estilo de la 2ª imagen del perejil: macros por 100 g (energía, proteínas,
-- grasas, carbohidratos) y 4 beneficios, renderizada programáticamente con
-- datos curados (scripts/product-images/nutrition-data.mjs) — NO con IA de
-- imagen, porque el dato nutrimental tiene que salir exacto.
--
-- PEREJIL: su infografía de Take.app (que venía como 2ª imagen desde
-- 00210) se reemplaza por la generada en el mismo estilo, para que todas
-- las infografías del sitio compartan plantilla.
--
-- Idempotente: re-ejecutarla deja el mismo estado (fija images a
-- [principal, infografía]).
-- ============================================================

BEGIN;

DO $$
DECLARE
  v_actualizados int;
  v_sin_dos int;
BEGIN
  CREATE TEMP TABLE _infog (slug text PRIMARY KEY) ON COMMIT DROP;
  INSERT INTO _infog (slug) VALUES
    ('acelga'),
    ('achiote'),
    ('aguacate-chunky-caja-7264kg'),
    ('aguacate-hass'),
    ('aguja-engorda'),
    ('ajo'),
    ('ajonjoli'),
    ('ala-adobada-bolsa-5kg'),
    ('ala-botanera-bolsa-5kg'),
    ('ala-habanero-bolsa-5kg'),
    ('ala-iqf-pilgrims-caja-12kg'),
    ('albahaca'),
    ('alfalfa-germinado'),
    ('almendras-500g'),
    ('amaranto'),
    ('anis'),
    ('apio-palitos-aderezo-mr-lucky'),
    ('arandano-fresco'),
    ('aros-cebolla-bolsa-907g'),
    ('arrachera-premium-sukarne'),
    ('arroz-blanco-1kg'),
    ('atun-saku'),
    ('avena'),
    ('azucar-refinada-5kg'),
    ('betabel'),
    ('blue-berry'),
    ('boneless-buffalo-freskecito'),
    ('boneless-natural-freskecito'),
    ('boneless-pechuga-pilgrims'),
    ('brisket-deshuesado'),
    ('brocoli'),
    ('cabeza-res-deshuesada'),
    ('cacahuate-enchilado'),
    ('cacahuate-japones'),
    ('cacahuate-natural-tostado'),
    ('cachete-res'),
    ('calabaza'),
    ('calamar-lonja-filete'),
    ('camaron-1620-gigante'),
    ('camaron-2125'),
    ('camaron-2630'),
    ('camaron-3135'),
    ('camaron-3640'),
    ('camaron-4150'),
    ('camaron-5160'),
    ('camaron-6170'),
    ('camaron-7190'),
    ('camaron-cabeza-2030'),
    ('camaron-cocido-100200'),
    ('camaron-cocido-4150'),
    ('canela-en-polvo'),
    ('carne-al-pastor-100'),
    ('carne-hamburguesa-arrachera-900g'),
    ('carne-hamburguesa-san-francisco-12kg'),
    ('carne-hamburguesa-sirloin-900g'),
    ('carne-molida-90-10'),
    ('carne-molida-de-pulpa'),
    ('carne-molida-economica'),
    ('carne-molida-especial'),
    ('carne-molida-pulpa-extralimp'),
    ('carne-molida-pulpa-natural'),
    ('cebolla-amarilla'),
    ('cebolla-cambray'),
    ('cebolla-morada'),
    ('chacal'),
    ('chamberete'),
    ('chamberete-cortado'),
    ('chamorro-puerco'),
    ('champinon'),
    ('chayote'),
    ('chicharo'),
    ('chicharron-pella'),
    ('chicharron-prensado'),
    ('chile-caribe'),
    ('chile-chilaca'),
    ('chile-colorin'),
    ('chile-de-la-tierra'),
    ('chile-habanero'),
    ('chile-jalapeno'),
    ('chile-mirasol'),
    ('chile-morita'),
    ('chile-pasado'),
    ('chile-poblano'),
    ('chorizo-grapa'),
    ('cicido-rabo'),
    ('cilantro'),
    ('ciruela-pasa'),
    ('clavo'),
    ('cocido-pecho-c-h'),
    ('coco-rayado'),
    ('cocoa-polvo-1kg'),
    ('codillo'),
    ('col-blanca'),
    ('coliflor'),
    ('comino-molido'),
    ('consome-de-pollo-1kg'),
    ('cordon-bleu-mini'),
    ('costilla-back-rib'),
    ('costilla-back-rib-tira-corta'),
    ('costilla-cargada-delantera'),
    ('costilla-cargada-prime'),
    ('costilla-puerco-cargada'),
    ('costilla-puerco-cargada-cortada'),
    ('costilla-tracera-chuleta'),
    ('costilla-tracera-engorda'),
    ('cuero-puerco'),
    ('curcuma'),
    ('deditos-papa-caja-10kg'),
    ('dedos-queso-bolsa-181kg'),
    ('desebrada-aldilla'),
    ('diezmillo-c-h-chuleta'),
    ('diezmillo-c-h-engorda'),
    ('ejote'),
    ('elote'),
    ('ensalada-cesar-mr-lucky'),
    ('ensalada-primavera-mr-lucky'),
    ('epazote'),
    ('esparrago'),
    ('espinaca'),
    ('espinazo'),
    ('espinazo-cargado'),
    ('filete-guitarra'),
    ('filete-salmon-premium'),
    ('filete-tilapia-35'),
    ('filete-tilapia-comercial-50'),
    ('frambuesa'),
    ('fresa'),
    ('frijol-negro-1kg'),
    ('gragea'),
    ('granola'),
    ('haba'),
    ('hamburguesa-bm-arrachera-caja-30pzs'),
    ('hamburguesa-bm-mezquite-caja-30pzs'),
    ('hamburguesa-bm-sirloin-caja-30pzs'),
    ('hamburguesa-empanizada-pilgrims'),
    ('hierbabuena-fresca'),
    ('hoja-de-laurel'),
    ('hueso-menudo'),
    ('jamaica'),
    ('jengibre-fresco'),
    ('jicama'),
    ('jitomate-cherry'),
    ('kale-organico-1kg'),
    ('kiwi'),
    ('labio-res'),
    ('lechuga-romana'),
    ('lenteja-1kg'),
    ('limon-agrio'),
    ('linaza'),
    ('lomo-ahumado-chimex'),
    ('lomo-ahumado-cortado'),
    ('lomo-ahumado-cubicado-1kg'),
    ('lomo-engorda-premium'),
    ('lomo-natural-cortado'),
    ('lomo-natural-puerco'),
    ('maiz-rosero'),
    ('mango-ataulfo'),
    ('manitas-puerco'),
    ('manteca-puerco'),
    ('manzana-golden'),
    ('medallon-atun-mexicano'),
    ('mejorana-fresca'),
    ('melon-chino'),
    ('melon-honeydew'),
    ('menta-fresca'),
    ('menudo-americano'),
    ('menudo-americano-cortado'),
    ('menudo-mexicano'),
    ('menudo-mexicano-cortado'),
    ('mojarra-importada'),
    ('morcon'),
    ('muslo-bate'),
    ('naranja-valencia'),
    ('nugget-pechuga-pilgrims'),
    ('nuggets-enchiladas-caja-10kg'),
    ('oregano-molido-100g'),
    ('paleta-engorda'),
    ('papa-blanca'),
    ('papa-conquest-14-caja-1633kg'),
    ('papa-conquest-delivery-38-sc-caja-1361kg'),
    ('papa-conquest-delivery-teja-65-caja-1361kg'),
    ('papa-curly-savory-caja-1361kg'),
    ('papa-dulce-recta-38-caja-680kg'),
    ('papa-francesa-14-payette-caja-1224kg'),
    ('papa-francesa-38-payette-caja-1361kg'),
    ('papa-gajo-10-cut-65-caja-1361kg'),
    ('papa-hash-brown-patty-caja-952kg'),
    ('papa-lisa-caja'),
    ('papa-megacrunch-14-caja-1224kg'),
    ('papa-ondulada-38-payette-caja-1361kg'),
    ('papa-rallada-hash-brown-caja-816kg'),
    ('papa-rejilla-savory-caja-1224kg'),
    ('papa-select-38-cascara-caja-1361kg'),
    ('papa-select-38-sc-caja-1361kg'),
    ('papa-select-516-sc-caja-1361kg'),
    ('papa-thunder-38-sc-caja-1361kg'),
    ('papaya-maradol'),
    ('pasas'),
    ('pata-res'),
    ('pechuga-grill-fc-pilgrims'),
    ('pechuga-media-mariposa'),
    ('pechuga-picante-emp-pilgrims'),
    ('pechuga-sh-am-soles-caja-10kg'),
    ('pechuga-sh-br-soles-caja-10kg'),
    ('pechuga-sh-pilgrims-caja-12kg'),
    ('pechuga-sin-hueso-br'),
    ('pepino'),
    ('pepita-de-calabaza'),
    ('pepita-de-girasol'),
    ('perejil'),
    ('pescuezo-res-con-hueso'),
    ('pescuezo-res-deshuesado'),
    ('pierna-puerco-cubicada'),
    ('pierna-puerco-natural'),
    ('pierna-puerco-natural-cortada'),
    ('piloncillo'),
    ('pimenton'),
    ('pimienta-negra-molida'),
    ('platano-macho'),
    ('pollo-empanizado-kfc-caja-1361kg'),
    ('pollo-entero-congelado-pilgrims-caja-145kg'),
    ('pork-belly-premium-tif'),
    ('pork-belly-seabord'),
    ('poro'),
    ('porter-house'),
    ('pozole-dona-conchita-10pzs'),
    ('pulpa-alto-vacio'),
    ('pulpa-bola'),
    ('pulpa-bola-negra-natural'),
    ('pulpa-milanesa'),
    ('pulpa-negra'),
    ('pulpa-sirloin-cubicada-1x1'),
    ('pulpo-12'),
    ('pulpo-24'),
    ('pulpo-cocido-picado-500g'),
    ('queso-crema-krol-barra-136kg'),
    ('queso-crema-reny-picot-136kg'),
    ('queso-crema-reny-picot-caja-8kg'),
    ('quinoa-1kg'),
    ('rabano'),
    ('rib-eye'),
    ('romero-fresco'),
    ('sal-de-mar-fina-1kg'),
    ('sandia'),
    ('semilla-chia-1kg'),
    ('suadero'),
    ('t-bone-engorda'),
    ('t-bone-engorda-premium'),
    ('tamarindo'),
    ('tapioca'),
    ('te-de-limon'),
    ('tender-empanizado-pilgrims'),
    ('tocino-cubicado-1kg'),
    ('tocino-rebanado'),
    ('tomahawk'),
    ('tomate-verde'),
    ('tomillo-fresco'),
    ('toronja'),
    ('trigo-entero'),
    ('tripa-puerco'),
    ('tripa-res-americana-1361'),
    ('tuetano-hueso-canoa'),
    ('tuetano-hueso-cortar'),
    ('tuna-fruta'),
    ('uva-negra'),
    ('zanahoria'),
    ('zancarron'),
    ('zarzamora');

  UPDATE public.products p
  SET images = jsonb_build_array(
        p.image_url,
        '/images/products/infografia/' || p.slug || '.webp'
      ),
      updated_at = now()
  FROM _infog i
  WHERE p.slug = i.slug
    AND p.is_visible
    AND p.image_url IS NOT NULL;

  GET DIAGNOSTICS v_actualizados = ROW_COUNT;

  -- Guarda: ningún producto visible de la lista queda con una sola imagen.
  SELECT count(*) INTO v_sin_dos
  FROM public.products p
  JOIN _infog i ON i.slug = p.slug
  WHERE p.is_visible
    AND (p.images IS NULL OR jsonb_array_length(p.images) < 2);

  IF v_sin_dos > 0 THEN
    RAISE WARNING '00215: % productos visibles quedaron sin 2ª imagen.', v_sin_dos;
  ELSE
    RAISE NOTICE '00215: % productos con infografía como 2ª imagen.', v_actualizados;
  END IF;
END $$;

COMMIT;
