-- ============================================================
-- 00217 — Imágenes e infografías de TODOS los productos no publicados.
--
-- QUE HACE
-- --------
-- Completa la ficha de los 252 productos ocultos que faltaban
-- (abarrotes, lácteos, carnes, pan, bebidas, limpieza y empaques):
-- 1. `image_url` reapuntado a la imagen de catálogo generada en
--    /images/products/ai/<slug>.webp (antes: fotos viejas de Take.app,
--    compartidas o ninguna).
-- 2. `images = [principal, infografía]`: la infografía nutrimental/de uso
--    como 2ª imagen, mismo patrón que 00215 y 00216.
--
-- SIGUEN OCULTOS: esto no publica nada; solo deja la ficha lista para
-- activarse desde /admin/productos.
--
-- Idempotente: fija image_url e images a su valor final, solo en productos
-- con is_visible = false.
-- ============================================================

BEGIN;

DO $$
DECLARE
  v_img int;
  v_total int;
BEGIN
  CREATE TEMP TABLE _ocultos (slug text PRIMARY KEY) ON COMMIT DROP;
  INSERT INTO _ocultos (slug) VALUES
    ('manzana-verde'),
    ('platano-tabasco'),
    ('mango-manila'),
    ('papa-cambray'),
    ('hongo-portobello'),
    ('arroz-blanco-5kg'),
    ('frijol-negro-5kg'),
    ('frijol-bayo-1kg'),
    ('frijol-peruano-1kg'),
    ('garbanzo-1kg'),
    ('aceite-canola-1l'),
    ('aceite-canola-5l'),
    ('aceite-de-maiz-1l'),
    ('aceite-de-oliva-1l'),
    ('manteca-vegetal'),
    ('pasta-spaghetti-500g'),
    ('pasta-codito-500g'),
    ('pasta-fideo-500g'),
    ('harina-de-maiz-1kg'),
    ('harina-de-trigo-1kg'),
    ('azucar-estandar-1kg'),
    ('azucar-glass-500g'),
    ('sal-gruesa-1kg'),
    ('pimienta-negra-molida-100g'),
    ('comino-molido-100g'),
    ('salsa-valentina-370ml'),
    ('salsa-maggi-200ml'),
    ('salsa-de-soya-500ml'),
    ('salsa-inglesa-250ml'),
    ('catsup-1kg'),
    ('mayonesa-1kg'),
    ('mostaza-400g'),
    ('consome-de-res-1kg'),
    ('vinagre-blanco-1l'),
    ('vinagre-de-manzana-1l'),
    ('mole-dona-maria-500g'),
    ('maicena-500g'),
    ('leche-entera-lala-1l'),
    ('leche-descremada-1l'),
    ('leche-evaporada-360ml'),
    ('media-crema-240ml'),
    ('leche-condensada-370ml'),
    ('huevo-blanco-18pz'),
    ('huevo-blanco-caja-30pz'),
    ('huevo-rojo-18pz'),
    ('queso-oaxaca-400g'),
    ('queso-fresco-500g'),
    ('queso-panela-400g'),
    ('queso-manchego-400g'),
    ('queso-crema-200g'),
    ('yogurt-natural-1l'),
    ('crema-acida-1l'),
    ('mantequilla-sin-sal-200g'),
    ('pechuga-pollo'),
    ('milanesa-de-pollo'),
    ('pierna-muslo-pollo'),
    ('alitas-de-pollo'),
    ('pollo-entero'),
    ('bistec-de-res'),
    ('milanesa-de-res'),
    ('carne-molida-80-20'),
    ('diezmillo-de-res'),
    ('falda-de-res'),
    ('costilla-de-res'),
    ('t-bone'),
    ('chuleta-de-cerdo'),
    ('lomo-de-cerdo'),
    ('costilla-de-cerdo'),
    ('jamon-de-pierna'),
    ('filete-de-tilapia'),
    ('filete-de-basa'),
    ('camaron-pacotilla'),
    ('camaron-u12-u15'),
    ('mojarra-entera'),
    ('huachinango-entero'),
    ('camaron-seco'),
    ('pan-bimbo-blanco'),
    ('pan-integral'),
    ('pan-hot-dog'),
    ('pan-hamburguesa'),
    ('tortillas-maiz'),
    ('tortillas-de-harina'),
    ('pan-de-ajo'),
    ('coca-cola-25l'),
    ('coca-cola-light-25l'),
    ('sprite-2l'),
    ('fanta-naranja-2l'),
    ('sidral-mundet-2l'),
    ('agua-bonafont-15l'),
    ('agua-mineral-15l'),
    ('agua-mineral-saborizada-15l'),
    ('jugo-jumex-1l'),
    ('concentrado-jamaica-1l'),
    ('concentrado-horchata-1l'),
    ('cerveza-corona-355ml'),
    ('cerveza-modelo-355ml'),
    ('cerveza-victoria-355ml'),
    ('cerveza-pacifico-355ml'),
    ('sabritas-clasicas-170g'),
    ('totopos-200g'),
    ('cacahuate-salado-200g'),
    ('galletas-marias-200g'),
    ('galletas-saladas-200g'),
    ('chocolate-abuelita'),
    ('cloro-1l'),
    ('cloro-5l'),
    ('jabon-zote-400g'),
    ('detergente-liquido-1l'),
    ('detergente-en-polvo-1kg'),
    ('desengrasante-1l'),
    ('limpiador-multiusos-500ml'),
    ('limpiavidrios-500ml'),
    ('jabon-lavaplatos-750ml'),
    ('fibras-para-trastes-3pz'),
    ('bolsas-de-basura-50pz'),
    ('servilletas-100pz'),
    ('papel-de-cocina-2pz'),
    ('guantes-de-latex-100pz'),
    ('verduras-congeladas-500g'),
    ('papas-a-la-francesa-1kg'),
    ('helado-vainilla-1l'),
    ('paletas-de-hielo-12pz'),
    ('filete-tilapia-congelado-1kg'),
    ('camaron-congelado-1kg'),
    ('nuggets-de-pollo-1kg'),
    ('deditos-de-pescado-1kg'),
    ('pan-brioche'),
    ('queso-cheddar-rebanado'),
    ('salchicha-jumbo'),
    ('pepinillos-encurtidos'),
    ('chiles-jalapenos-encurtidos'),
    ('papas-congeladas'),
    ('aceite-vegetal'),
    ('aros-de-cebolla'),
    ('salsa-bbq'),
    ('frijoles-refritos'),
    ('huevo-fresco'),
    ('aderezo-ranch'),
    ('pierna-de-cerdo'),
    ('achiote-en-pasta'),
    ('chiles-secos-surtidos'),
    ('chile-guajillo'),
    ('manteca-de-cerdo'),
    ('flor-de-calabaza'),
    ('chile-chipotle'),
    ('alga-nori'),
    ('jengibre-encurtido'),
    ('huesos-de-cerdo'),
    ('fideos-ramen'),
    ('carne-de-cerdo-molida'),
    ('col-china'),
    ('pasta-wonton'),
    ('pasta-de-tamarindo'),
    ('salsa-de-anguila'),
    ('pure-de-tomate-enlatado'),
    ('queso-mozzarella'),
    ('albahaca-fresca'),
    ('champinones-frescos'),
    ('pasta-fettuccine'),
    ('queso-parmesano'),
    ('crema-para-batir'),
    ('queso-gorgonzola'),
    ('queso-provolone'),
    ('pasta-para-lasana'),
    ('pure-de-jitomate'),
    ('queso-mascarpone'),
    ('cafe-espresso'),
    ('cocoa-en-polvo'),
    ('salsa-buffalo'),
    ('queso-azul'),
    ('pan-molido'),
    ('papas-cambray'),
    ('miel-de-abeja'),
    ('queso-asadero'),
    ('chile-mulato'),
    ('chile-ancho'),
    ('chile-pasilla'),
    ('chocolate-de-mesa'),
    ('maiz-cacahuazintle'),
    ('queso-de-cabra'),
    ('masa-para-tamal'),
    ('hoja-de-maiz'),
    ('caldo-de-pollo'),
    ('filete-de-pescado-blanco'),
    ('jugo-de-tomate'),
    ('salsa-picante'),
    ('sal-de-grano'),
    ('costillas-de-cerdo'),
    ('azucar-mascabado'),
    ('cebolla-en-polvo'),
    ('suadero-de-res'),
    ('salsa-verde'),
    ('harina-para-hot-cakes'),
    ('miel-de-maple'),
    ('cafe-en-grano'),
    ('atun-fresco'),
    ('pan-para-crutones'),
    ('aceituna-kalamata'),
    ('queso-feta'),
    ('tortilla-integral'),
    ('yogur-griego'),
    ('chispas-de-chocolate'),
    ('yemas-de-huevo'),
    ('pan-pita'),
    ('eneldo-fresco'),
    ('pasta-filo'),
    ('harina-pan'),
    ('maiz-tierno'),
    ('queso-de-mano'),
    ('queso-blanco'),
    ('frijoles-rojos'),
    ('cerveza-clara'),
    ('chile-en-polvo'),
    ('jalapenos-en-escabeche'),
    ('tequila-blanco'),
    ('licor-de-naranja'),
    ('ron-blanco'),
    ('servilleta-mesa-economica-caja'),
    ('contenedor-llevar-una-division-caja'),
    ('bolsa-basura-grande-uso-rudo'),
    ('papel-aluminio-alimentario-rollo'),
    ('vaso-caliente-12oz-caja'),
    ('tapa-vaso-caliente-12oz-caja'),
    ('bolsa-kraft-mediana-llevar'),
    ('papel-envolver-burritos'),
    ('recipiente-salsa-2oz-caja'),
    ('tapa-recipiente-salsa-2oz-caja'),
    ('toalla-papel-manos-caja'),
    ('vaso-frio-16oz-caja'),
    ('tapa-vaso-frio-16oz-caja'),
    ('contenedor-llevar-tres-divisiones-caja'),
    ('pelicula-adherente-alimentaria-rollo'),
    ('papel-higienico-institucional-caja'),
    ('tenedor-desechable-caja'),
    ('cuchara-desechable-caja'),
    ('portavasos-carton-paquete'),
    ('lavatrastes-liquido-garrafa'),
    ('desengrasante-cocina-garrafa'),
    ('jabon-liquido-manos-garrafa'),
    ('limpiador-pisos-garrafa'),
    ('fibra-lavado-utensilios-paquete'),
    ('aceite-vegetal-institucional'),
    ('azucar-estandar-saco'),
    ('frijol-pinto-seco-saco'),
    ('arroz-blanco-saco'),
    ('consome-pollo-bote-institucional'),
    ('pure-tomate-institucional'),
    ('cafe-grano-espresso-1kg'),
    ('leche-entera-uht-caja'),
    ('azucar-sobres-caja'),
    ('chocolate-polvo-bebidas-bolsa'),
    ('jarabe-vainilla-bebidas-botella');

  UPDATE public.products p
  SET image_url = '/images/products/ai/' || p.slug || '.webp',
      images = jsonb_build_array(
        '/images/products/ai/' || p.slug || '.webp',
        '/images/products/infografia/' || p.slug || '.webp'
      ),
      updated_at = now()
  FROM _ocultos o
  WHERE p.slug = o.slug
    AND p.is_visible = false;

  GET DIAGNOSTICS v_img = ROW_COUNT;

  SELECT count(*) INTO v_total FROM _ocultos;
  IF v_img <> v_total THEN
    RAISE WARNING '00217: se esperaban % productos y se actualizaron % (¿alguno está visible?).', v_total, v_img;
  ELSE
    RAISE NOTICE '00217: % productos ocultos con imagen AI + infografía (siguen ocultos).', v_img;
  END IF;
END $$;

COMMIT;
